In [1]:
import pandas as pd
import re
from geopy.geocoders import Nominatim
from functools import partial
geolocator = Nominatim(user_agent="Mi_aplicacion_intento1")
geocode = partial(geolocator.geocode, language="en")


In [2]:
df = pd.read_csv('Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.csv')
df.head()

Timestamp How old are you?                       Industry  \
0  4/27/2021 11:02:10            25-34   Education (Higher Education)   
1  4/27/2021 11:02:22            25-34              Computing or Tech   
2  4/27/2021 11:02:38            25-34  Accounting, Banking & Finance   
3  4/27/2021 11:02:41            25-34                     Nonprofits   
4  4/27/2021 11:02:42            25-34  Accounting, Banking & Finance   

                                  Job title Additional context on job title  \
0        Research and Instruction Librarian                             NaN   
1  Change & Internal Communications Manager                             NaN   
2                      Marketing Specialist                             NaN   
3                           Program Manager                             NaN   
4                        Accounting Manager                             NaN   

  Annual salary  Other monetary comp Currency Currency - other  \
0        55,000                  0.0      USD              NaN   
1        54,600               4000.0      GBP              NaN   
2        34,000                  NaN      USD              NaN   
3        62,000               3000.0      USD              NaN   
4        60,000               7000.0      USD              NaN   

  Additional context on income         Country           State         City  \
0                          NaN   United States   Massachusetts       Boston   
1                          NaN  United Kingdom             NaN    Cambridge   
2                          NaN              US       Tennessee  Chattanooga   
3                          NaN             USA       Wisconsin    Milwaukee   
4                          NaN              US  South Carolina   Greenville   

  Overall years of professional experience Years of experience in field  \
0                                5-7 years                    5-7 years   
1                             8 - 10 years                    5-7 years   
2                              2 - 4 years                  2 - 4 years   
3                             8 - 10 years                    5-7 years   
4                             8 - 10 years                    5-7 years   

  Highest level of education completed      Gender   Race  
0                      Master's degree       Woman  White  
1                       College degree  Non-binary  White  
2                       College degree       Woman  White  
3                       College degree       Woman  White  
4                       College degree       Woman  White

In [3]:
df.shape

(27663, 18)

## Homogenización de variables salario_actual y compensaciones.

Vamos a comenzar por esta homogenización debido al alto grado de dificultad de la homogenización en las variables geográficas. 

Primero observamos la naturaleza de la variable

In [4]:
print("Valores", list(df["Annual salary"].sort_values()))

Valores ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '00', '1', '1,000', '1,050,000', '1,080,000', '1,100,000', '1,100,000', '1,100,000', '1,100,000', '1,150,000', '1,150,000', '1,150,000', '1,200,000', '1,200,000', '1,260,000', '1,300,000', '1,300,000', '1,324,000', '1,334,782', '1,360,000', '1,400,000', '1,442', '1,650,000', '1,900,000', '10,000', '10,000', '10,500', '10,500', '10,800', '100', '100', '100', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100,000', '100

In [5]:
df["Currency"].unique()

array(['USD', 'GBP', 'CAD', 'EUR', 'AUD/NZD', 'Other', 'CHF', 'ZAR',
       'SEK', 'HKD', 'JPY'], dtype=object)

Como se puede observar hay un valor de moneda que es otro. Esto puede "Ensuciar" mucho los datos, puesto que cualquier valor que asumamos puede generar un cambio muy grande en la muestra.

In [6]:
print("Tamaño muestra:", len(list(df[df["Currency"] == "Other"]["Annual salary"])), "Datos:" ,list(df[df["Currency"] != "Other"]["Annual salary"]))

Tamaño muestra: 145 Datos: ['55,000', '54,600', '34,000', '62,000', '60,000', '62,000', '33,000', '50,000', '112,000', '45,000', '47,500', '62,000', '100,000', '52,000', '32,000', '24,000', '85,000', '59,000', '98,000', '54,000', '74,000', '50,000', '63,000', '96,000', '44,500', '60,000', '62,000', '48,000', '140,000', '80,000', '39,000', '125,000', '230,000', '110,000', '50,000', '68,000', '41,000', '76,000', '78,000', '37,000', '100,000', '35,000', '65,000', '187,500', '110,000', '66,625', '144,600', '200,850', '120,000', '97,500', '96,000', '53,000', '95,000', '72,000', '52,000', '106,000', '115,000', '100,500', '33,200', '52,000', '52,000', '79,000', '104,000', '75,000', '52,000', '70,000', '84,000', '53,000', '34,000', '38,000', '87,000', '122,000', '45,000', '45,000', '88,000', '71,000', '71,000', '75,000', '80,000', '125,000', '65,000', '36,000', '55,000', '90,000', '105,000', '60,000', '65,000', '85,000', '39,520', '115,000', '76,000', '180,000', '90,000', '19,300', '65,000', '

Por otra parte, se observa que los datos que tienen currency en "other" son 145 y tienen dimensiones muy cambiantes. Para efectos de este ejercicio vamos a quitar esos datos. En la vida real, tocartía hacer un estudio al respecto, posiblemente algún método de autorrellenado, por ejemplo poner el promedio de otras condiciones en el salario funcionaria. 

In [7]:
df = df[df["Currency"] != "Other"]

Ahora, con el resto de la muestra observar y realizar lo siguiente:

Rápidamente, parece que los errores principales puenten ser: 
1. El uso de comas cuando hablamso de miles o millones.
2. algunos número con problemas de dimensiones, 1, 100, 1000. El principal problema en esto es saber la dimensión correta. Dado que es sueldo anual y que 12.000.000 COP es demasiado bajo (teniendo en cuenta que el salario minimo es más que eso en Colombia, asumimos que cualquier valor menor que 12.000.000 es ese valor *1000.

Por otra parte, asumimos lo siquiente de las tasas de cambio:
1. USD \$3,917.52
2. GBP \$5,434.23
3. CAD \$3,094.32
4. EUR \$4,471.69
5. AUD/NZD \$2,811.54 Asumimos que es AUD
6. CHF \$4,253.90
7. ZAR \$258.89
8. SEK \$422.01
9. HKD \$505.09
10. JPY \$34.13

In [8]:
TRM = {"USD":3917.52, "GBP": 5343.23, "CAD":3094.32, "EUR": 4471.69, "AUD/NZD": 2811.54,
       "CHF":4253.90, "ZAR":258.89, "SEK":422.01, "HKD":505.09, "JPY":34.13}

df["Other monetary comp"] = df["Other monetary comp"].fillna(0)

df.loc[:,"salario_anual"] = df["Annual salary"].apply(lambda x: re.sub('[^0-9]+', '', x))
df.loc[:,"salario_anual"] = pd.to_numeric(df["salario_anual"], downcast="float")

df.loc[:,"compensaciones"] = df["Other monetary comp"].apply(lambda x: re.sub('[^0-9]+', '', str(x)))
df.loc[:,"compensaciones"] = pd.to_numeric(df["compensaciones"], downcast="float")

df.loc[:,"salario_anual"] = [df.loc[i, "salario_anual"]*TRM[df.loc[i, "Currency"]] for i in df.index]
df.loc[:,"compensaciones"] = [df.loc[i, "compensaciones"]*TRM[df.loc[i, "Currency"]] for i in df.index]
df.loc[:,"salario_anual"] = df["salario_anual"].apply(lambda x: x*1000 if x < 12000000 else x)

In [9]:
df["Total_ingresos"]  = df.loc[:,"salario_anual"] + df.loc[:,"compensaciones"]

## Estandarización localización 

Intenté hacerlo por expresiones regulares pero la cantidad de ciudades y paises lo hacian muy dispendioso. Por lo tanto, utilicé un servicio que se llama Nominatim, es como google maps pero completamente gratis (y tiene un performace menos bueno). Inicialmente, cree una variable lugar que se compone de la concatenación de ciudad, estado y pais. De esta forma busqué cada uno de los "lugares".

In [10]:
df["Lugar"] = df["City"] + ", " + df["State"] + ", " + df["Country"]
df["Lugar"] = df["Lugar"].apply(lambda x: re.sub('[^A-Za-z, ]+', '', str(x).upper()))


In [11]:
lugares = {}
errores = []
contador = 0
for c in df["Lugar"].unique():
    contador += 1
    try:
        lugares[c] = geolocator.geocode(c.replace(".", ""), exactly_one=True,language="en", namedetails=True, addressdetails=True).raw["address"]
        print(contador, c, lugares[c])
    except:
        errores.append(c)

1 BOSTON, MASSACHUSETTS, UNITED STATES {'city': 'Boston', 'county': 'Suffolk County', 'state': 'Massachusetts', 'postcode': '02102', 'country': 'United States', 'country_code': 'us'}
2 NAN {'state': 'Nangarhar Province', 'country': 'Afghanistan', 'country_code': 'af'}
3 CHATTANOOGA, TENNESSEE, US {'city': 'Chattanooga', 'county': 'Hamilton County', 'state': 'Tennessee', 'postcode': '818', 'country': 'United States', 'country_code': 'us'}
4 MILWAUKEE, WISCONSIN, USA {'city': 'Milwaukee', 'county': 'Milwaukee County', 'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
5 GREENVILLE, SOUTH CAROLINA, US {'city': 'Greenville', 'county': 'Greenville County', 'state': 'South Carolina', 'country': 'United States', 'country_code': 'us'}
6 HANOVER, NEW HAMPSHIRE, USA {'town': 'Hanover', 'county': 'Grafton County', 'state': 'New Hampshire', 'country': 'United States', 'country_code': 'us'}
7 COLUMBIA, SOUTH CAROLINA, USA {'city': 'Columbia', 'county': 'Richland County', 'state

53 DISTRICT OF COLUMBIA, DISTRICT OF COLUMBIA, UNITED STATES {'amenity': 'University of California Washington Center', 'house_number': '1608', 'road': 'Rhode Island Avenue Northwest', 'city': 'Washington', 'state': 'District of Columbia', 'postcode': '20036', 'country': 'United States', 'country_code': 'us'}
54 BLOOMINGTON, ILLINOIS, UNITED STATES {'city': 'Bloomington', 'county': 'McLean County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
55 DENVER, COLORADO, US {'city': 'Denver', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
56 NEW YORK CITY, NEW YORK, UNITED STATES {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
57 COLUMBIA, SOUTH CAROLINA, UNITED STATES {'city': 'Columbia', 'county': 'Richland County', 'state': 'South Carolina', 'country': 'United States', 'country_code': 'us'}
60 CHAMPAIGN, ILLINOIS, USA {'city': 'Champaign', 'county': 'Champaign County', 'state': 'Illinois', 'country'

107 SAN ANTONIO, TEXAS, US {'city': 'San Antonio', 'county': 'Bexar County', 'state': 'Texas', 'postcode': '78205', 'country': 'United States', 'country_code': 'us'}
108 MCLEAN, VIRGINIA, UNITED STATES {'locality': 'McLean', 'hamlet': 'Brookhaven', 'county': 'Fairfax County', 'state': 'Virginia', 'postcode': '22101', 'country': 'United States', 'country_code': 'us'}
109 ARDMORE, OKLAHOMA, UNITED STATES {'town': 'Ardmore', 'county': 'Carter County', 'state': 'Oklahoma', 'country': 'United States', 'country_code': 'us'}
110 COLUMBUS, OHIO, US {'city': 'Columbus', 'county': 'Franklin County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
111 SHAKER HTS, OHIO, US {'town': 'Shaker Heights', 'county': 'Cuyahoga County', 'state': 'Ohio', 'postcode': '44120', 'country': 'United States', 'country_code': 'us'}
112 CHARLESTON, SOUTH CAROLINA, USA {'city': 'Charleston', 'county': 'Charleston County', 'state': 'South Carolina', 'country': 'United States', 'country_code': 'us'}


161 STAMFORD, CONNECTICUT, UNITED STATES {'city': 'Stamford', 'county': 'Fairfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
162 NEWPORT, OREGON, UNITED STATES {'town': 'Newport', 'county': 'Lincoln County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
163 LOS ANGELES, CALIFORNIA, UNITED STATES OF AMERICA {'city': 'Los Angeles', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
164 NEW BRUNSWICK, NEW JERSEY, UNITED STATES {'city': 'New Brunswick', 'county': 'Middlesex County', 'state': 'New Jersey', 'postcode': '08901', 'country': 'United States', 'country_code': 'us'}
166 SPOKANE, WASHINGTON, USA {'city': 'Spokane', 'county': 'Spokane County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
167 DURHAM, NORTH CAROLINA, US {'city': 'Durham', 'county': 'Durham County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}


214 FAIRFIELD, CONNECTICUT, UNITED STATES {'town': 'Fairfield', 'county': 'Fairfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
215 MANCHESTER, CONNECTICUT, US {'boundary': 'Central Manchester', 'town': 'Vernon', 'county': 'Tolland County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
216 PITTSBURGH, PENNSYLVANIA, US {'city': 'Pittsburgh', 'county': 'Allegheny County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
217 DFW, TEXAS, USA {'aeroway': 'Dallas/Fort Worth International Airport', 'city': 'Grapevine', 'county': 'Tarrant County', 'state': 'Texas', 'postcode': '75261', 'country': 'United States', 'country_code': 'us'}
218 DC, DISTRICT OF COLUMBIA, USA {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
219 WILMINGTON, NORTH CAROLINA, US {'city': 'Wilmington', 'county': 'New Hanover County', 'state': 'North Carolina', 'country': 'Un

269 SOMERSET, NEW JERSEY, USA {'place': 'Somerset', 'township': 'Franklin Township', 'county': 'Somerset County', 'state': 'New Jersey', 'postcode': '08873', 'country': 'United States', 'country_code': 'us'}
270 SAN FRANCISCO, CALIFORNIA, USA {'city': 'San Francisco', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
271 NORMAL, ILLINOIS, UNITED STATES {'town': 'Normal', 'county': 'McLean County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
272 BOSTON, MASSACHUSETTS, UNITED STATES  {'city': 'Boston', 'county': 'Suffolk County', 'state': 'Massachusetts', 'postcode': '02102', 'country': 'United States', 'country_code': 'us'}
273 EGLIN AFB, FLORIDA, UNITED STATES {'locality': 'Eglin Air Force Base', 'county': 'Okaloosa County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
275 RALEIGH, NORTH CAROLINA, US {'city': 'Raleigh', 'county': 'Wake County', 'state': 'North Carolina', 'country': 'United States', 'country_code

322 LANSING , MICHIGAN, UNITED STATES  {'city': 'Lansing', 'county': 'Ingham County', 'state': 'Michigan', 'country': 'United States', 'country_code': 'us'}
323 PITTSBURGH , PENNSYLVANIA, UNITED STATES {'city': 'Pittsburgh', 'county': 'Allegheny County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
324 LAS VEGAS, NEVADA, UNITED STATES {'city': 'Las Vegas', 'county': 'Clark County', 'state': 'Nevada', 'country': 'United States', 'country_code': 'us'}
326 CAMBRIDGE, MASSACHUSETTS, USA {'city': 'Cambridge', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '02139-9991', 'country': 'United States', 'country_code': 'us'}
327 ALBANY, NEW YORK, USA {'city': 'Albany', 'county': 'Albany County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
328 OAK PARK, ILLINOIS, USA {'town': 'Oak Park', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
329 IRONWOOD, MICHIGAN, US  {'town': 'Ir

378 BETHESDA, MARYLAND, USA {'boundary': 'Bethesda', 'city': 'Bethesda', 'county': 'Montgomery County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
379 PORTSMOUTH , VIRGINIA, USA {'city': 'Portsmouth', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
380 LOUISVILLE, KENTUCKY, UNITED STATES {'city': 'Louisville', 'county': 'Jefferson County', 'state': 'Kentucky', 'postcode': '40202-2923', 'country': 'United States', 'country_code': 'us'}
381 NEWPORT BEACH, CALIFORNIA, USA {'town': 'Newport Beach', 'city': 'Newport Beach', 'county': 'Orange County', 'state': 'California', 'postcode': '92658', 'country': 'United States', 'country_code': 'us'}
382 SOUTH TEXAS, TEXAS, USA {'road': 'South Texas', 'town': 'Eagle Pass', 'county': 'Maverick County', 'state': 'Texas', 'postcode': '78852', 'country': 'United States', 'country_code': 'us'}
383 KIRTLAND, NEW MEXICO, UNITED STATES {'city': 'Kirtland', 'county': 'San Juan County', 'state': 'New Mexico'

430 CINCINNATI , OHIO, UNITED STATES {'city': 'Cincinnati', 'county': 'Hamilton County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
431 BETHLEHEM, PENNSYLVANIA, UNITED STATES {'city': 'Bethlehem', 'county': 'Northampton County', 'state': 'Pennsylvania', 'postcode': '18108', 'country': 'United States', 'country_code': 'us'}
432 NEW ULM, MINNESOTA, USA {'town': 'New Ulm', 'city': 'New Ulm', 'county': 'Brown County', 'state': 'Minnesota', 'postcode': '56073', 'country': 'United States', 'country_code': 'us'}
433 ROCKVILLE, MARYLAND, UNITED STATES {'town': 'Rockville', 'county': 'Montgomery County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
434 WACO , TEXAS, UNITED STATES  {'city': 'Waco', 'county': 'McLennan County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
435 BOISE, IDAHO, US {'city': 'Boise', 'county': 'Ada County', 'state': 'Idaho', 'postcode': '83701', 'country': 'United States', 'country_code': 'us'}
436

482 SUBURB OF CHICAGO, ILLINOIS, UNITED STATES {'suburb': 'Forest Glen', 'city': 'Chicago', 'municipality': 'Jefferson Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60646', 'country': 'United States', 'country_code': 'us'}
483 GAITHERSBURG, MARYLAND, USA {'town': 'Gaithersburg', 'county': 'Montgomery County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
484 NY METRO, NEW JERSEY, USA {'building': 'Performance Foodservice — Metro NY', 'road': 'IKEA Drive', 'retail': 'The Elizabeth Center', 'city': 'Elizabeth', 'county': 'Union County', 'state': 'New Jersey', 'postcode': '07206', 'country': 'United States', 'country_code': 'us'}
485 MEDFORD, OREGON, USA {'city': 'Medford', 'county': 'Jackson County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
486 NORFOLK, VIRGINIA, UNITED STATES {'city': 'Norfolk', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
487 SILVER SPRING, MARYLAND, UNITED STATES {'b

535 GREATER CHICAGO , ILLINOIS, USA {'suburb': 'Greater Grand Crossing', 'city': 'Chicago', 'municipality': 'Hyde Park Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
536 BROOKLYN, NEW YORK, UNITED STATES {'suburb': 'Brooklyn', 'city_district': 'Kings County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
537 TALLAHASSEE, FLORIDA, US {'city': 'Tallahassee', 'county': 'Leon County', 'state': 'Florida', 'postcode': '32399-1300', 'country': 'United States', 'country_code': 'us'}
539 WASHINGTON , DISTRICT OF COLUMBIA, USA {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
540 NORTHWEST GEORGIA, GEORGIA, UNITED STATES {'neighbourhood': 'Northwest Woods', 'town': 'Hinesville', 'county': 'Liberty County', 'state': 'Georgia', 'postcode': '31313', 'country': 'United States', 'country_code': 'us'}
541 JACKSONVILLE, FLORIDA, UNITED STATES {'city': 'Jacksonvill

585 TORRINGTON , MASSACHUSETTS, UNITED STATES {'road': 'Torrington Lane', 'neighbourhood': 'Nabnasset', 'town': 'Westford', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01886-2179', 'country': 'United States', 'country_code': 'us'}
586 COLUMBIA, MISSOURI, USA {'city': 'Columbia', 'county': 'Boone County', 'state': 'Missouri', 'country': 'United States', 'country_code': 'us'}
588 CARSON CITY, NEVADA, UNITED STATES {'city': 'Carson City', 'state': 'Nevada', 'country': 'United States', 'country_code': 'us'}
589 SALISBURY, MARYLAND, USA {'city': 'Salisbury', 'county': 'Wicomico County', 'state': 'Maryland', 'postcode': '21803', 'country': 'United States', 'country_code': 'us'}
590 CRYSTAL CITY, VIRGINIA, USA {'suburb': 'Crystal City', 'city': 'Arlington', 'county': 'Arlington County', 'state': 'Virginia', 'postcode': '22202', 'country': 'United States', 'country_code': 'us'}
591 ST LOUIS PARK, MINNESOTA, UNITED STATES {'town': 'Saint Louis Park', 'city': 'Saint Loui

639 SAN ANTONIO , TEXAS, UNITED STATES {'city': 'San Antonio', 'county': 'Bexar County', 'state': 'Texas', 'postcode': '78205', 'country': 'United States', 'country_code': 'us'}
640 PHILLY, PENNSYLVANIA, USA {'city': 'Philadelphia', 'county': 'Philadelphia County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
641 KINGSTON, MASSACHUSETTS, US {'town': 'Kingston', 'city': 'Kingston', 'county': 'Plymouth County', 'state': 'Massachusetts', 'postcode': '02364', 'country': 'United States', 'country_code': 'us'}
642 INDIANAPOLIS , INDIANA, USA {'city': 'Indianapolis', 'county': 'Marion County', 'state': 'Indiana', 'country': 'United States', 'country_code': 'us'}
644 LAWRENCE, MASSACHUSETTS, USA {'city': 'Lawrence', 'county': 'Essex County', 'state': 'Massachusetts', 'postcode': '01840', 'country': 'United States', 'country_code': 'us'}
645 SAN JOSE , CALIFORNIA, USA {'city': 'San Jose', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United Sta

698 BUFFALO, NEW YORK, US {'city': 'Buffalo', 'county': 'Erie County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
699 DETROIT, MI, MICHIGAN, USA {'city': 'Detroit', 'county': 'Wayne County', 'state': 'Michigan', 'country': 'United States', 'country_code': 'us'}
700 BOCA RATON , FLORIDA, UNITED STATES {'city': 'Boca Raton', 'county': 'Palm Beach County', 'state': 'Florida', 'postcode': '33432', 'country': 'United States', 'country_code': 'us'}
701 BOSTON SUBURBS, MASSACHUSETTS, USA {'suburb': 'East Boston', 'city': 'Boston', 'county': 'Suffolk County', 'state': 'Massachusetts', 'postcode': '02128', 'country': 'United States', 'country_code': 'us'}
702 BOULDER, COLORADO, US {'city': 'Boulder', 'county': 'Boulder County', 'state': 'Colorado', 'postcode': '80306', 'country': 'United States', 'country_code': 'us'}
703 LARKSPUR, CALIFORNIA, UNITED STATES {'town': 'Larkspur', 'city': 'Larkspur', 'county': 'Marin County', 'state': 'California', 'postcode': '94939', 

750 FREDERICK, MARYLAND, USA {'city': 'Frederick', 'county': 'Frederick County', 'state': 'Maryland', 'postcode': '21701-4546', 'country': 'United States', 'country_code': 'us'}
751 BALTIMORE, MARYLAND, US {'city': 'Baltimore', 'state': 'Maryland', 'postcode': '21203', 'country': 'United States', 'country_code': 'us'}
752 OAKLAND , CALIFORNIA, USA {'city': 'Oakland', 'county': 'Alameda County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
753 WASHINGTON, DC, DISTRICT OF COLUMBIA, US {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
755 LINCOLN, NEBRASKA, UNITED STATES {'city': 'Lincoln', 'county': 'Lancaster County', 'state': 'Nebraska', 'postcode': '68508', 'country': 'United States', 'country_code': 'us'}
756 JACKSONVILLE, FLORIDA, US {'city': 'Jacksonville', 'county': 'Duval County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
757 MANCHESTER, NEW HAMPSHIRE, USA {'city': 'Man

804 BORON, CALIFORNIA, UNITED STATES {'boundary': 'Boron', 'village': 'Boron', 'county': 'Kern County', 'state': 'California', 'postcode': '93516-1645', 'country': 'United States', 'country_code': 'us'}
805 SYRACUSE, NEW YORK, UNITED STATES {'city': 'Syracuse', 'county': 'Onondaga County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
806 BROOKLYN, NEW YORK, US {'suburb': 'Brooklyn', 'city_district': 'Kings County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
807 NA, SOUTH CAROLINA, UNITED STATES {'tourism': 'The Museum of Greenwood, South Carolina', 'house_number': '106', 'road': 'Main Street North', 'town': 'Greenwood', 'county': 'Greenwood County', 'state': 'South Carolina', 'postcode': '29647', 'country': 'United States', 'country_code': 'us'}
808 TUCSON, ARIZONA, USA {'city': 'Tucson', 'county': 'Pima County', 'state': 'Arizona', 'postcode': '85701', 'country': 'United States', 'country_code': 'us'}
809 CHESTER SPRINGS, PA, PENNS

855 SALT LAKE CITY, UTAH, US {'city': 'Salt Lake City', 'county': 'Salt Lake County', 'state': 'Utah', 'postcode': '84139', 'country': 'United States', 'country_code': 'us'}
856 SHORELINE, WASHINGTON, UNITED STATES {'town': 'Shoreline', 'county': 'King County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
857 HORSHAM, PENNSYLVANIA, US {'boundary': 'Horsham', 'town': 'Horsham', 'city': 'Horsham Township', 'county': 'Montgomery County', 'state': 'Pennsylvania', 'postcode': '19044', 'country': 'United States', 'country_code': 'us'}
858 VALDOSTA, GEORGIA, USA {'city': 'Valdosta', 'county': 'Lowndes County', 'state': 'Georgia', 'postcode': '31604', 'country': 'United States', 'country_code': 'us'}
859 NORMAL, ILLINOIS, UNITED STATES  {'town': 'Normal', 'county': 'McLean County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
860 MONTVALE, NEW JERSEY, USA {'village': 'Montvale', 'county': 'Bergen County', 'state': 'New Jersey', 'postcode': 

905 , MONTANA, USA {'waterway': 'USA Reservoir Number 2 Dam', 'county': 'Garfield County', 'state': 'Montana', 'country': 'United States', 'country_code': 'us'}
906 WALTHAM, MASSACHUSETTS, USA {'city': 'Waltham', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
907 SOMERSET, NEW JERSEY, US {'place': 'Somerset', 'township': 'Franklin Township', 'county': 'Somerset County', 'state': 'New Jersey', 'postcode': '08873', 'country': 'United States', 'country_code': 'us'}
908 CHANTILLY, VIRGINIA, UNITED STATES {'boundary': 'Chantilly', 'town': 'Chantilly', 'county': 'Fairfax County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
909 VIRGINIA, VIRGINIA, US {'town': 'Virginia', 'city': 'Virginia', 'county': 'Saint Louis County', 'state': 'Minnesota', 'postcode': '55792', 'country': 'United States', 'country_code': 'us'}
910 CINCINNATI, KENTUCKY, USA {'aeroway': 'Cincinnati/Northern Kentucky International Airport', 

957 MOSCOW, IDAHO, UNITED STATES {'town': 'Moscow', 'county': 'Latah County', 'state': 'Idaho', 'country': 'United States', 'country_code': 'us'}
958 MENOMONEE FALLS, WISCONSIN, UNITED STATES {'village': 'Menomonee Falls', 'county': 'Waukesha County', 'state': 'Wisconsin', 'postcode': '53051', 'country': 'United States', 'country_code': 'us'}
959 JOHNSTON, RHODE ISLAND, UNITED STATES {'town': 'Johnston', 'county': 'Providence County', 'state': 'Rhode Island', 'country': 'United States', 'country_code': 'us'}
962 WACO, TEXAS, USA {'city': 'Waco', 'county': 'McLennan County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
963 RALEIGH NC, NORTH CAROLINA, USA {'city': 'Raleigh', 'county': 'Wake County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
964 OVERLAND PARK, KANSAS, USA {'city': 'Overland Park', 'county': 'Johnson County', 'state': 'Kansas', 'postcode': '66204', 'country': 'United States', 'country_code': 'us'}
965 LINCOLN, NE, N

1009 ROMNEY, WEST VIRGINIA, US {'town': 'Romney', 'county': 'Hampshire County', 'state': 'West Virginia', 'postcode': '26757', 'country': 'United States', 'country_code': 'us'}
1010 REMOTE, WISCONSIN, UNITED STATES {'amenity': 'Multicultural Student Services (Remote Office)', 'house_number': '1110', 'road': 'Broadway Street South', 'neighbourhood': 'South Menomonie', 'town': 'Menomonie', 'county': 'Dunn County', 'state': 'Wisconsin', 'postcode': '54751', 'country': 'United States', 'country_code': 'us'}
1012 ACTON, MA, MASSACHUSETTS, USA {'town': 'Acton', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1013 EUFAULA, ALABAMA, USA {'town': 'Eufaula', 'city': 'Eufaula', 'county': 'Barbour County', 'state': 'Alabama', 'postcode': '36072', 'country': 'United States', 'country_code': 'us'}
1015 RENO, NEVADA, UNITED STATES {'city': 'Reno', 'county': 'Washoe County', 'state': 'Nevada', 'country': 'United States', 'country_code': 'us'}
1

1067 QUINCY, ILLINOIS, UNITED STATES {'city': 'Quincy', 'county': 'Adams County', 'state': 'Illinois', 'postcode': '62301', 'country': 'United States', 'country_code': 'us'}
1068 HUNTSVILLE, ALABAMA, US {'city': 'Huntsville', 'county': 'Madison County', 'state': 'Alabama', 'postcode': '35804', 'country': 'United States', 'country_code': 'us'}
1069 POUGHKEEPSIE , NEW YORK, US {'city': 'Poughkeepsie', 'county': 'Dutchess County', 'state': 'New York', 'postcode': '12601', 'country': 'United States', 'country_code': 'us'}
1071 CHICAGO AREA, ILLINOIS, UNITED STATES  {'industrial': 'United Parcel Service - Chicago Area Consolidation Hub', 'village': 'Hodgkins', 'municipality': 'Lyons Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
1072 WESTERN KS, KANSAS, UNITED STATES {'road': 'Western', 'town': 'Holton', 'county': 'Jackson County', 'state': 'Kansas', 'postcode': '66436', 'country': 'United States', 'country_code': 'us'}
1073 DENVER

1116 BISMARCK, NORTH DAKOTA, UNITED STATES {'city': 'Bismarck', 'county': 'Burleigh County', 'state': 'North Dakota', 'country': 'United States', 'country_code': 'us'}
1117 WATERTOWN, WISCONSIN, UNITED STATES {'town': 'Watertown', 'county': 'Jefferson County', 'state': 'Wisconsin', 'postcode': '53094', 'country': 'United States', 'country_code': 'us'}
1119 ALPHARETTA, GEORGIA, US {'town': 'Alpharetta', 'county': 'Fulton County', 'state': 'Georgia', 'postcode': '300009', 'country': 'United States', 'country_code': 'us'}
1120 PROVIDENCE, RHODE ISLAND, USA  {'city': 'Providence', 'county': 'Providence County', 'state': 'Rhode Island', 'country': 'United States', 'country_code': 'us'}
1121 LANSDALE, PENNSYLVANIA, US {'town': 'Lansdale', 'county': 'Montgomery County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
1122 EDISON, NEW JERSEY, USA {'township': 'Edison', 'county': 'Middlesex County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'u

1170 NORTHVILLE, MICHIGAN, USA {'village': 'Northville', 'county': 'Wayne County', 'state': 'Michigan', 'postcode': '48167', 'country': 'United States', 'country_code': 'us'}
1171 OLYMPIC PENINSULA, WASHINGTON, US {'place': 'Olympic Peninsula', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
1172 WORCESTER AREA, MASSACHUSETTS, US {'landuse': 'Worcester Commons Construction Area', 'town': 'Amherst', 'county': 'Hampshire County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1173 NORTHAMPTON, MASSACHUSETTS, USA {'city': 'Northampton', 'county': 'Hampshire County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1174 WEST PALM BEACH, FLORIDA, UNITED STATES {'city': 'West Palm Beach', 'county': 'Palm Beach County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
1175 FAYETTEVILLE, NORTH CAROLINA, UNITED STATES {'city': 'Fayetteville', 'county': 'Cumberland County', 'state': 'North Carol

1223 FORT WORTH, TEXAS, US {'city': 'Fort Worth', 'county': 'Tarrant County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
1224 DISTRICT OF COLUMBIA, DISTRICT OF COLUMBIA, US {'amenity': 'University of California Washington Center', 'house_number': '1608', 'road': 'Rhode Island Avenue Northwest', 'city': 'Washington', 'state': 'District of Columbia', 'postcode': '20036', 'country': 'United States', 'country_code': 'us'}
1225 EAST LIVERPOOL, OHIO, UNITED STATES {'town': 'East Liverpool', 'county': 'Columbiana County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
1226 NORTHAMPTON , MASSACHUSETTS, US {'city': 'Northampton', 'county': 'Hampshire County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1227 FLORENCE, SOUTH CAROLINA, USA {'city': 'Florence', 'county': 'Florence County', 'state': 'South Carolina', 'postcode': '29502', 'country': 'United States', 'country_code': 'us'}
1228 CINCINNATI, KENTUCKY, OHIO, UNIT

1274 RESTON, VIRGINIA, USA {'locality': 'Reston', 'county': 'Fairfax County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
1275 CORALVILLE, IOWA, USA {'town': 'Coralville', 'county': 'Johnson County', 'state': 'Iowa', 'postcode': '52241', 'country': 'United States', 'country_code': 'us'}
1276 SAN FRANCISCO , CALIFORNIA, UNITED STATES {'city': 'San Francisco', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1277 BETHEL, MAINE, USA {'town': 'Bethel', 'county': 'Oxford County', 'state': 'Maine', 'postcode': '04217', 'country': 'United States', 'country_code': 'us'}
1278 MEMPHIS, TENNESSEE, US {'city': 'Memphis', 'county': 'Shelby County', 'state': 'Tennessee', 'postcode': '3813', 'country': 'United States', 'country_code': 'us'}
1279 BOSTON MA, MASSACHUSETTS, UNITED STATES {'city': 'Boston', 'county': 'Suffolk County', 'state': 'Massachusetts', 'postcode': '02102', 'country': 'United States', 'country_code': 'us'}
1281 RIVERDALE, UTAH, US

1327 ISELIN, NEW JERSEY, UNITED STATES {'place': 'Iselin', 'township': 'Woodbridge Township', 'county': 'Middlesex County', 'state': 'New Jersey', 'postcode': '08830', 'country': 'United States', 'country_code': 'us'}
1330 REMOTE, WASHINGTON, USA {'shop': 'Remote Control Hobbies', 'road': 'Southeast 272nd Street', 'town': 'Covington', 'county': 'King County', 'state': 'Washington', 'postcode': '98042', 'country': 'United States', 'country_code': 'us'}
1331 IDAHO FALLS, IDAHO, UNITED STATES OF AMERICA {'city': 'Idaho Falls', 'county': 'Bonneville County', 'state': 'Idaho', 'postcode': '83403', 'country': 'United States', 'country_code': 'us'}
1332 BERKELEY , CALIFORNIA, USA  {'amenity': 'University of California, Berkeley', 'road': 'Shattuck Avenue', 'neighbourhood': 'LeConte', 'city': 'Berkeley', 'county': 'Alameda County', 'state': 'California', 'postcode': '95704', 'country': 'United States', 'country_code': 'us'}
1333 OAKLAND, CALIFORNIA, UNITED STATES {'city': 'Oakland', 'county': 

1379 SANDY, UTAH, USA {'city': 'Sandy', 'county': 'Salt Lake County', 'state': 'Utah', 'postcode': '84070', 'country': 'United States', 'country_code': 'us'}
1380 CUPERTINO, CALIFORNIA, UNITED STATES {'city': 'Cupertino', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1382 GLEN ALLEN, VIRGINIA, USA {'boundary': 'Glen Allen', 'town': 'Glen Allen', 'county': 'Henrico County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
1383 DERBY, CT, CONNECTICUT, USA {'town': 'Derby', 'county': 'New Haven County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
1384 SHREVEPORT, LOUISIANA, USA {'city': 'Shreveport', 'county': 'Caddo Parish', 'state': 'Louisiana', 'country': 'United States', 'country_code': 'us'}
1385 WOONSOCKET, RHODE ISLAND, USA {'city': 'Woonsocket', 'county': 'Providence County', 'state': 'Rhode Island', 'postcode': '02895', 'country': 'United States', 'country_code': 'us'}
1

1430 SAINT LOUIS, MISSOURI, USA {'city': 'Saint Louis', 'state': 'Missouri', 'country': 'United States', 'country_code': 'us'}
1431 TOLEDO, OHIO, USA {'city': 'Toledo', 'county': 'Lucas County', 'state': 'Ohio', 'postcode': '43659', 'country': 'United States', 'country_code': 'us'}
1432 NYC , NEW YORK, UNITED STATES {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
1433 FAIRFIELD, NEW JERSEY, USA {'hamlet': 'Fairfield', 'township': 'Howell Township', 'county': 'Monmouth County', 'state': 'New Jersey', 'postcode': '07731', 'country': 'United States', 'country_code': 'us'}
1434 SOMERVILLE, MASSACHUSETTS, US {'city': 'Somerville', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '02143', 'country': 'United States', 'country_code': 'us'}
1436 IRVING, TEXAS, USA {'city': 'Irving', 'county': 'Dallas County', 'state': 'Texas', 'postcode': '75061', 'country': 'United States', 'country_code': 'us'}
1437 BOTHELL, WASHINGTON, US {'town'

1491 FAIRFIELD COUNTY, CONNECTICUT, USA {'county': 'Fairfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
1492 CAMBRIDGE , MASSACHUSETTS, USA  {'city': 'Cambridge', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '02139-9991', 'country': 'United States', 'country_code': 'us'}
1494 ROCKFORD, ILLINOIS, UNITED STATES {'city': 'Rockford', 'municipality': 'Rockford Township', 'county': 'Winnebago County', 'state': 'Illinois', 'postcode': '61104', 'country': 'United States', 'country_code': 'us'}
1495 EVERETT, WASHINGTON, USA {'city': 'Everett', 'county': 'Snohomish County', 'state': 'Washington', 'postcode': '98120', 'country': 'United States', 'country_code': 'us'}
1496 MADISON, WISCONSIN, UNITED STATES OF AMERICA {'city': 'Madison', 'county': 'Dane County', 'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
1497 NA, TEXAS, USA {'aeroway': 'NA', 'road': 'Security Patrol Road', 'city': 'Houston', 'county': 'Harr

1551 CHICAGO , ILLINOIS, UNITED STATES  {'city': 'Chicago', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
1552 FOLSOM, CALIFORNIA, USA {'town': 'Folsom', 'county': 'Sacramento County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1553 SANTA BARBARA, CALIFORNIA, USA {'city': 'Santa Barbara', 'county': 'Santa Barbara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1555 METAIRIE , LOUISIANA, UNITED STATES {'locality': 'Metairie', 'county': 'Jefferson Parish', 'state': 'Louisiana', 'country': 'United States', 'country_code': 'us'}
1556 PLYMOUTH MEETING, PENNSYLVANIA, UNITED STATES {'locality': 'Plymouth Meeting', 'city': 'Whitemarsh Township', 'county': 'Montgomery County', 'state': 'Pennsylvania', 'postcode': '19444', 'country': 'United States', 'country_code': 'us'}
1558 SOMERVILLE , NEW JERSEY, US {'town': 'Somerville', 'county': 'Somerset County', 'state': 'New Jersey', 'coun

1606 UPPER VALLEY, NEW HAMPSHIRE, US {'retail': 'Upper Valley Plaza', 'city': 'Lebanon', 'county': 'Grafton County', 'state': 'New Hampshire', 'postcode': '03784', 'country': 'United States', 'country_code': 'us'}
1607 SUNNYVALE , CALIFORNIA, US {'city': 'Sunnyvale', 'county': 'Santa Clara County', 'state': 'California', 'postcode': '94807', 'country': 'United States', 'country_code': 'us'}
1608 FAIRBANKS , ALASKA, UNITED STATES {'city': 'Fairbanks', 'county': 'Fairbanks North Star', 'state': 'Alaska', 'country': 'United States', 'country_code': 'us'}
1609 CARTERSVILLE , GEORGIA, USA {'town': 'Cartersville', 'county': 'Bartow County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
1610 HILLSDALE, MICHIGAN, USA {'county': 'Hillsdale County', 'state': 'Michigan', 'country': 'United States', 'country_code': 'us'}
1611 PORTLAND, ME, MAINE, USA {'city': 'Portland', 'county': 'Cumberland County', 'state': 'Maine', 'country': 'United States', 'country_code': 'us'}
1612 

1662 CORPUS CHRISTI, TEXAS, UNITED STATES {'city': 'Corpus Christi', 'county': 'Nueces County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
1663 ALEXANDRIA , VIRGINIA, USA  {'city': 'Alexandria', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
1665 FORT EUSTIS, VIRGINIA, UNITED STATES {'landuse': 'Fort Eustis', 'county': 'Newport News', 'state': 'Virginia', 'postcode': '23604', 'country': 'United States', 'country_code': 'us'}
1666 KING OF PRUSSIA, PENNSYLVANIA, UNITED STATES {'boundary': 'King of Prussia', 'town': 'King of Prussia', 'city': 'Upper Merion Township', 'county': 'Montgomery County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
1667 OSCEOLA, ARKANSAS, UNITED STATES {'town': 'Osceola', 'county': 'Mississippi County', 'state': 'Arkansas', 'postcode': '72370', 'country': 'United States', 'country_code': 'us'}
1668 WATERLOO, ILLINOIS, USA {'town': 'Waterloo', 'city': 'Waterloo', 'county': 'Monroe Coun

1716 BALTIMORE, MD, MARYLAND, US {'city': 'Baltimore', 'state': 'Maryland', 'postcode': '21203', 'country': 'United States', 'country_code': 'us'}
1718 MEDFORD, MASSACHUSETTS, USA {'town': 'Medford', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1719 WORCESTER, MASSACHUSETTS, USA {'city': 'Worcester', 'county': 'Worcester County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1720 KINGSBURG, CALIFORNIA, USA {'town': 'Kingsburg', 'county': 'Fresno County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1721 RIVERVIEW, FLORIDA, US {'town': 'Riverview', 'county': 'Hillsborough County', 'state': 'Florida', 'postcode': '33568', 'country': 'United States', 'country_code': 'us'}
1723 BALTIMORE , MARYLAND, UNITED STATES {'city': 'Baltimore', 'state': 'Maryland', 'postcode': '21203', 'country': 'United States', 'country_code': 'us'}
1724 COLUMBUS, INDIANA, UNITED STATES {'town': '

1774 ANDOVER, MASSACHUSETTS, US {'amenity': 'Phillips Academy Andover', 'road': 'Main Street', 'town': 'Andover', 'county': 'Essex County', 'state': 'Massachusetts', 'postcode': '01810', 'country': 'United States', 'country_code': 'us'}
1775 NANTICOKE, PENNSYLVANIA, USA {'town': 'Nanticoke', 'city': 'Nanticoke', 'county': 'Luzerne County', 'state': 'Pennsylvania', 'postcode': '18634', 'country': 'United States', 'country_code': 'us'}
1776 SANTA CRUZ, CALIFORNIA, US {'county': 'Santa Cruz County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1777 MARLBOROUGH, MASSACHUSETTS, USA {'city': 'Marlborough', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01752', 'country': 'United States', 'country_code': 'us'}
1778 PLANTATION , FLORIDA, UNITED STATES  {'suburb': 'Plantation', 'county': 'Broward County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
1779 BEACHWOOD, OHIO, UNITED STATES {'town': 'Beachwood', 'county': 'Cuy

1834 SAN LUIS OBISPO, CALIFORNIA, USA {'county': 'San Luis Obispo County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
1835 INDIANAPOLIS, INDIANA, US {'city': 'Indianapolis', 'county': 'Marion County', 'state': 'Indiana', 'country': 'United States', 'country_code': 'us'}
1836 REMOTE, MARYLAND, USA {'shop': 'Remote Control Hobbies', 'road': 'York Road', 'city': 'Towson', 'county': 'Baltimore County', 'state': 'Maryland', 'postcode': '21093', 'country': 'United States', 'country_code': 'us'}
1837 SAINT CHARLES, ILLINOIS, UNITED STATES {'landuse': 'Saint Patricks Catholic Church', 'town': 'St. Charles', 'county': 'Kane County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
1838 WATERTOWN, MASSACHUSETTS, USA {'town': 'Watertown', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1839 REMOTE, MINNESOTA, US {'natural': 'Remote Lake', 'county': 'Aitkin County', 'state': 'Minnesota', '

1886 SACRAMENTO , CALIFORNIA, US {'city': 'Sacramento', 'county': 'Sacramento County', 'state': 'California', 'postcode': '95814', 'country': 'United States', 'country_code': 'us'}
1887 ALLENTOWN, PENNSYLVANIA, UNITED STATES {'city': 'Allentown', 'county': 'Lehigh County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
1888 MADERA, CALIFORNIA, USA {'city': 'Madera', 'county': 'Madera County', 'state': 'California', 'postcode': '93637', 'country': 'United States', 'country_code': 'us'}
1889 ASHLAND, WISCONSIN, USA {'county': 'Ashland County', 'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
1890 ROCHESTER HILLS, MICHIGAN, UNITED STATES {'town': 'Rochester Hills', 'county': 'Oakland County', 'state': 'Michigan', 'country': 'United States', 'country_code': 'us'}
1891 BUFFALO, MINNESOTA, UNITED STATES {'town': 'Buffalo', 'county': 'Wright County', 'state': 'Minnesota', 'postcode': '55313', 'country': 'United States', 'country_code': 'us'}


1940 LINDON, UTAH, UNITED STATES {'village': 'Lindon', 'county': 'Utah County', 'state': 'Utah', 'country': 'United States', 'country_code': 'us'}
1941 CAMBRIDGE , MASSACHUSETTS, UNITED STATES {'city': 'Cambridge', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '02139-9991', 'country': 'United States', 'country_code': 'us'}
1942 MISSOURI CITY, TEXAS, UNITED STATES {'town': 'Missouri City', 'city': 'Missouri City', 'county': 'Fort Bend County', 'state': 'Texas', 'postcode': '77477', 'country': 'United States', 'country_code': 'us'}
1944 FORT LEE, NEW JERSEY, USA {'town': 'Fort Lee', 'county': 'Bergen County', 'state': 'New Jersey', 'postcode': '07024', 'country': 'United States', 'country_code': 'us'}
1945 WELLS, MAINE, UNITED STATES {'town': 'Wells', 'county': 'York County', 'state': 'Maine', 'postcode': '04090', 'country': 'United States', 'country_code': 'us'}
1946 ABERDEEN, WASHINGTON, UNITED STATES {'city': 'Aberdeen', 'county': 'Grays Harbor County', 'state': 

1992 HILLSBORO, OREGON, UNITED STATES {'city': 'Hillsboro', 'county': 'Washington County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
1993 WALLA WALLA, WASHINGTON, USA {'city': 'Walla Walla', 'county': 'Walla Walla County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
1995 WALTHAM, MASSACHUSETTS, USA  {'city': 'Waltham', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
1996 WELLINGTON, KANSAS, USA {'town': 'Wellington', 'county': 'Sumner County', 'state': 'Kansas', 'postcode': '67152', 'country': 'United States', 'country_code': 'us'}
1997 NEW YORK, NORTH CAROLINA, USA {'road': 'New York Avenue', 'town': 'Elizabeth City', 'county': 'Pasquotank County', 'state': 'North Carolina', 'postcode': '27909', 'country': 'United States', 'country_code': 'us'}
1998 CENTRAL OHIO, OHIO, UNITED STATES {'quarter': 'Central', 'city': 'Cleveland', 'county': 'Cuyahoga County', 'state': 'Ohio', '

2046 MOREHEAD, KENTUCKY, USA {'town': 'Morehead', 'village': 'Morehead', 'county': 'Rowan County', 'state': 'Kentucky', 'postcode': '40351', 'country': 'United States', 'country_code': 'us'}
2047 PHOENIX , ARIZONA, UNITED STATES {'city': 'Phoenix', 'county': 'Maricopa County', 'state': 'Arizona', 'postcode': '85004-1905', 'country': 'United States', 'country_code': 'us'}
2048 PEARISBURG , VIRGINIA, USA {'town': 'Pearisburg', 'county': 'Giles County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
2049 FALCON HEIGHTS, MINNESOTA, USA {'village': 'Falcon Heights', 'county': 'Ramsey County', 'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
2051 NORTHEAST OHIO, OHIO, UNITED STATES {'amenity': 'Northeast Ohio Medical University', 'road': 'Bradley Road', 'village': 'Rootstown', 'municipality': 'Rootstown Township', 'county': 'Portage County', 'state': 'Ohio', 'postcode': '44272', 'country': 'United States', 'country_code': 'us'}
2052 SUNNYVALE, C

2101 MANHATTAN, KANSAS, UNITED STATES OF AMERICA {'city': 'Manhattan', 'county': 'Riley County', 'state': 'Kansas', 'postcode': '66502-6322', 'country': 'United States', 'country_code': 'us'}
2102 LEWISTON, MAINE, UNITED STATES {'city': 'Lewiston', 'county': 'Androscoggin County', 'state': 'Maine', 'postcode': '04240', 'country': 'United States', 'country_code': 'us'}
2103 BARTLESVILLE, OKLAHOMA, US {'city': 'Bartlesville', 'county': 'Washington County', 'state': 'Oklahoma', 'postcode': '74004', 'country': 'United States', 'country_code': 'us'}
2104 GURLEY, ALABAMA, USA {'city': 'Gurley', 'county': 'Madison County', 'state': 'Alabama', 'country': 'United States', 'country_code': 'us'}
2105 HOUSTON, TX, TEXAS, UNITED STATES OF AMERICA {'city': 'Houston', 'county': 'Harris County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
2106 DOWNERS GROVE, ILLINOIS, UNITED STATES OF AMERICA {'town': 'Downers Grove', 'village': 'Downers Grove', 'county': 'DuPage County', 'stat

2148 SKILLMAN, NEW JERSEY, USA {'hamlet': 'Skillman', 'township': 'Montgomery Township', 'county': 'Somerset County', 'state': 'New Jersey', 'postcode': '08504', 'country': 'United States', 'country_code': 'us'}
2150 MIDDLETOWN, DELAWARE, USA {'town': 'Middletown', 'county': 'New Castle County', 'state': 'Delaware', 'postcode': '19709-4689', 'country': 'United States', 'country_code': 'us'}
2151 ANNANDALE VA, VIRGINIA, USA {'boundary': 'Annandale', 'town': 'Annandale', 'county': 'Fairfax County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
2152 MARLTON, NJ, NEW JERSEY, UNITED STATES {'place': 'Marlton', 'township': 'Evesham Township', 'county': 'Burlington County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
2153 NEW YORK CITY, FLORIDA, UNITED STATES {'road': 'New York Street', 'city': 'Miami', 'county': 'Miami-Dade County', 'state': 'Florida', 'postcode': '33133', 'country': 'United States', 'country_code': 'us'}
2154 MURRIETA, C

2204 WINCHESTER, TENNESSEE, USA {'town': 'Winchester', 'city': 'Winchester', 'county': 'Franklin County', 'state': 'Tennessee', 'postcode': '37398', 'country': 'United States', 'country_code': 'us'}
2205 LAGUNA HILLS, CALIFORNIA, UNITED STATES {'town': 'Laguna Hills', 'county': 'Orange County', 'state': 'California', 'postcode': '92653', 'country': 'United States', 'country_code': 'us'}
2206 EASTERN IOWA, IOWA, USA {'aeroway': 'Eastern Iowa Airport', 'road': '76th Avenue Southwest', 'city': 'Cedar Rapids', 'county': 'Linn County', 'state': 'Iowa', 'postcode': '52404', 'country': 'United States', 'country_code': 'us'}
2207 SHEBOYGAN, WI, WISCONSIN, USA {'city': 'Sheboygan', 'county': 'Sheboygan County', 'state': 'Wisconsin', 'postcode': '53081', 'country': 'United States', 'country_code': 'us'}
2208 SAINT LOUIS , MISSOURI, UNITED STATES  {'city': 'Saint Louis', 'state': 'Missouri', 'country': 'United States', 'country_code': 'us'}
2209 TROY, MICHIGAN, USA {'town': 'Troy', 'county': 'Oak

2256  , ALASKA, USA {'man_made': 'Lake Hood Seaplane Base, Anchorage, Alaska, USA', 'road': 'Enstrom Circle', 'county': 'Anchorage', 'state': 'Alaska', 'country_code': 'us', 'administrative': 'Anchorage'}
2257 WHITE MARSH , MARYLAND, UNITED STATES  {'boundary': 'White Marsh', 'village': 'White Marsh', 'county': 'Baltimore County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
2260 SILVER SPRING, MARYLAND, US {'boundary': 'Silver Spring', 'city': 'Silver Spring', 'county': 'Montgomery County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
2261 ASHEVILLE , NORTH CAROLINA, UNITED STATES {'city': 'Asheville', 'county': 'Buncombe County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
2262 MEAD, COLORADO, USA {'town': 'Mead', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
2263 NAMPA, IDAHO, US {'city': 'Nampa', 'county': 'Canyon County', 'state': 'Idaho', 'postcode': '83686', 'country': '

2309 GATESVILLE, TEXAS, USA {'town': 'Gatesville', 'county': 'Coryell County', 'state': 'Texas', 'postcode': '76599', 'country': 'United States', 'country_code': 'us'}
2310 PROVO, UTAH, USA {'city': 'Provo', 'county': 'Utah County', 'state': 'Utah', 'postcode': '84606', 'country': 'United States', 'country_code': 'us'}
2312 NORWALK, CONNECTICUT, USA {'city': 'Norwalk', 'county': 'Fairfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
2313 PALM BEACH, FL, FLORIDA, USA {'county': 'Palm Beach County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
2314 EAU CLAIRE, WI, WISCONSIN, US {'city': 'Eau Claire', 'county': 'Eau Claire County', 'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
2315 HATTIESBURG , MISSISSIPPI, UNITED STATES {'city': 'Hattiesburg', 'county': 'Forrest County', 'state': 'Mississippi', 'postcode': '39403', 'country': 'United States', 'country_code': 'us'}
2316 GLENWOOD SPRINGS , COLORADO, 

2354 NORTH BAY, CALIFORNIA, USA {'waterway': 'North Bay', 'county': 'Humboldt County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
2355 EFFINGHAM, ILLINOIS, USA {'county': 'Effingham County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
2356 COTTAGE GROVE, MINNESOTA, US {'town': 'Cottage Grove', 'county': 'Washington County', 'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
2357 HAMPTON, IOWA, UNITED STATES {'town': 'Hampton', 'county': 'Franklin County', 'state': 'Iowa', 'postcode': '50441', 'country': 'United States', 'country_code': 'us'}
2358 PELHAM, NEW HAMPSHIRE, UNITED STATES  {'village': 'Pelham', 'county': 'Hillsborough County', 'state': 'New Hampshire', 'postcode': '03076', 'country': 'United States', 'country_code': 'us'}
2359 CHESAPEAKE, VIRGINIA, USA {'city': 'Chesapeake', 'state': 'Virginia', 'postcode': '23322', 'country': 'United States', 'country_code': 'us'}
2360 UPSTATE NY, NEW YORK, UNITED

2408 MELBOURNE, FLORIDA, UNITED STATES {'city': 'Melbourne', 'county': 'Brevard County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
2409 WAYLAND, MASSACHUSETTS, USA {'city': 'Wayland', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01778', 'country': 'United States', 'country_code': 'us'}
2412 MINNEAPOLIS, MINNESOTA, UNITED STATES  {'city': 'Minneapolis', 'county': 'Hennepin County', 'state': 'Minnesota', 'postcode': '55488', 'country': 'United States', 'country_code': 'us'}
2413 GOODYEAR, ARIZONA, UNITED STATES  {'town': 'Goodyear', 'city': 'Goodyear', 'county': 'Maricopa County', 'state': 'Arizona', 'postcode': '85395', 'country': 'United States', 'country_code': 'us'}
2415 PEORIA, IL, ILLINOIS, UNITED STATES {'city': 'Peoria', 'county': 'Peoria County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
2416 FAIRBANKS, ALASKA, US {'city': 'Fairbanks', 'county': 'Fairbanks North Star', 'state': 'Alaska', 'country': 

2462 HARTLAND, MICHIGAN, UNITED STATES {'hamlet': 'Hartland', 'town': 'Hartland Township', 'county': 'Livingston County', 'state': 'Michigan', 'postcode': '48353', 'country': 'United States', 'country_code': 'us'}
2463 TUSCALOOSA, ALABAMA, USA {'city': 'Tuscaloosa', 'county': 'Tuscaloosa County', 'state': 'Alabama', 'country': 'United States', 'country_code': 'us'}
2464 NYC, NEW YORK, UNITED STATES OF AMERICA {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
2465 WILMINGTON, NORTH CAROLINA, UNITED STATES {'city': 'Wilmington', 'county': 'New Hanover County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
2466 CLEVELAND, OHIO, UNITED STATES  {'city': 'Cleveland', 'county': 'Cuyahoga County', 'state': 'Ohio', 'postcode': '44113', 'country': 'United States', 'country_code': 'us'}
2468 LAS VEGAS , NEVADA, USA {'city': 'Las Vegas', 'county': 'Clark County', 'state': 'Nevada', 'country': 'United States', 'country_code': 

2526 STAMFORD, CT, CONNECTICUT, USA {'city': 'Stamford', 'county': 'Fairfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
2527 BURBANK, CALIFORNIA, USA {'city': 'Burbank', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
2528 THAYNE, WYOMING, US {'village': 'Thayne', 'town': 'Thayne', 'county': 'Lincoln County', 'state': 'Wyoming', 'postcode': '83127', 'country': 'United States', 'country_code': 'us'}
2529 WARMINSTER, PENNSYLVANIA, USA {'town': 'Warminster', 'city': 'Warminster Township', 'county': 'Bucks County', 'state': 'Pennsylvania', 'postcode': '18974', 'country': 'United States', 'country_code': 'us'}
2530 PASADENA, CALIFORNIA, US {'city': 'Pasadena', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
2531 WASHINGTON DC, VIRGINIA, US {'road': 'Francis Scott Key Bridge', 'suburb': 'Georgetown', 'city': 'Washington', 'county': 'Arling

2577 SANTA FE, NEW MEXICO, UNITED STATES OF AMERICA {'city': 'Santa Fe', 'county': 'Santa Fe County', 'state': 'New Mexico', 'country': 'United States', 'country_code': 'us'}
2579 WORCESTER, MASSACHUSETTS, US {'city': 'Worcester', 'county': 'Worcester County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
2580 EAST CHICAGO, INDIANA, USA {'town': 'East Chicago', 'county': 'Lake County', 'state': 'Indiana', 'postcode': '46312', 'country': 'United States', 'country_code': 'us'}
2581 TOPEKA , KANSAS, UNITED STATES {'city': 'Topeka', 'county': 'Shawnee County', 'state': 'Kansas', 'postcode': '66603-3758', 'country': 'United States', 'country_code': 'us'}
2582 BETHLEHEM, PENNSYLVANIA, US {'city': 'Bethlehem', 'county': 'Northampton County', 'state': 'Pennsylvania', 'postcode': '18108', 'country': 'United States', 'country_code': 'us'}
2583 DC, DISTRICT OF COLUMBIA, USA  {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_

2633 WEST WARWICK , RHODE ISLAND, USA  {'town': 'West Warwick', 'county': 'Kent County', 'state': 'Rhode Island', 'postcode': '02893', 'country': 'United States', 'country_code': 'us'}
2634 ARLINGTON, WASHINGTON, UNITED STATES {'town': 'Arlington', 'county': 'Snohomish County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
2635 LOS ANGELES, CALIFORNIA, UNITED STATES  {'city': 'Los Angeles', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
2636 WEST CHESTER, PENNSYLVANIA, USA {'town': 'West Chester', 'county': 'Chester County', 'state': 'Pennsylvania', 'postcode': '19383', 'country': 'United States', 'country_code': 'us'}
2637 TUCSON, ARIZONA, UTAH, US {'road': 'West Utah Street', 'city': 'Tucson', 'county': 'Pima County', 'state': 'Arizona', 'postcode': '85706', 'country': 'United States', 'country_code': 'us'}
2638 NEWTOWN, CONNECTICUT, UNITED STATES {'city_district': 'Newtown', 'town': 'Newtown', 'coun

2688 WINSTON SALEM , NORTH CAROLINA, UNITED STATES  {'city': 'Winston-Salem', 'county': 'Forsyth County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
2689 MORGANTOWN , WEST VIRGINIA, UNITED STATES {'city': 'Morgantown', 'county': 'Monongalia County', 'state': 'West Virginia', 'country': 'United States', 'country_code': 'us'}
2690 PHILADELPHIA, PENNSYLVANIA, UNITED STATES  {'city': 'Philadelphia', 'county': 'Philadelphia County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
2691 RICHMOND, VIRGINIA, VIRGINIA {'city': 'Richmond', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
2692 WILMINGTON, NEW YORK, UNITED STATES {'municipality': 'Wilmington', 'county': 'Essex County', 'state': 'New York', 'postcode': '12997', 'country': 'United States', 'country_code': 'us'}
2693 SUDBURY, MASSACHUSETTS, UNITED STATES {'town': 'Sudbury', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01776', 'co

2739 FRAMINGHAM, MASSACHUSETTS, USA {'city': 'Framingham', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
2740 SHELTON, CONNECTICUT, USA {'town': 'Shelton', 'county': 'Fairfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
2741 ORLANDO , FLORIDA, UNITED STATES {'city': 'Orlando', 'county': 'Orange County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
2742 RURAL CALIFORNIA, CALIFORNIA, UNITED STATES {'road': 'Rural Lane', 'residential': 'San Joaquin Hills', 'town': 'Laguna Niguel', 'county': 'Orange County', 'state': 'California', 'postcode': '92677', 'country': 'United States', 'country_code': 'us'}
2743 ALBUQUERQUE , NEW MEXICO, USA  {'city': 'Albuquerque', 'county': 'Bernalillo County', 'state': 'New Mexico', 'postcode': '87102', 'country': 'United States', 'country_code': 'us'}
2744 CYPRESS, CALIFORNIA, US {'town': 'Cypress', 'county': 'Orange County', 'state': '

2792 CONNECTICUT, CONNECTICUT, US {'town': 'Cornwall', 'county': 'Litchfield County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
2793 INDIAN HEAD, MARYLAND, UNITED STATES {'town': 'Indian Head', 'county': 'Charles County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
2794 REMOTE, OHIO, USA {'office': 'Remote Research Yurt', 'road': 'Jordan Creek Crossing trail', 'county': 'Lake County', 'state': 'Ohio', 'postcode': '44077', 'country': 'United States', 'country_code': 'us'}
2795 LOGAN , UTAH, US {'town': 'Logan', 'county': 'Cache County', 'state': 'Utah', 'country': 'United States', 'country_code': 'us'}
2797 FRENCH CAMP, CALIFORNIA, USA {'locality': 'French Camp', 'city': 'Stockton', 'county': 'San Joaquin County', 'state': 'California', 'postcode': '95231', 'country': 'United States', 'country_code': 'us'}
2798 ALLEN, TEXAS, UNITED STATES {'town': 'Allen', 'county': 'Collin County', 'state': 'Texas', 'country': 'United States', 

2847 BRENTWOOD , TENNESSEE, US {'town': 'Brentwood', 'county': 'Williamson County', 'state': 'Tennessee', 'postcode': '37027', 'country': 'United States', 'country_code': 'us'}
2848 MERIDIAN, IDAHO, USA {'city': 'Meridian', 'county': 'Ada County', 'state': 'Idaho', 'country': 'United States', 'country_code': 'us'}
2850 FAIRBANKS, ALASKA, USA {'city': 'Fairbanks', 'county': 'Fairbanks North Star', 'state': 'Alaska', 'country': 'United States', 'country_code': 'us'}
2851 SUBURBAN PHILADELPHIA , PENNSYLVANIA, US {'railway': 'Suburban Station', 'road': 'Underground Concourse', 'neighbourhood': 'Rittenhouse Square', 'suburb': 'Center City', 'city': 'Philadelphia', 'county': 'Philadelphia County', 'state': 'Pennsylvania', 'postcode': '19103', 'country': 'United States', 'country_code': 'us'}
2852 BOSTON, NEW JERSEY, US {'office': 'Boston Consulting Group', 'house_number': '466', 'road': 'Springfield Avenue', 'town': 'Summit', 'county': 'Union County', 'state': 'New Jersey', 'postcode': '0790

2904 LAKE JACKSON, TEXAS, USA {'town': 'Lake Jackson', 'county': 'Brazoria County', 'state': 'Texas', 'postcode': '77566', 'country': 'United States', 'country_code': 'us'}
2906 BELLEVILLE, ILLINOIS, USA {'town': 'Belleville', 'county': 'Saint Clair County', 'state': 'Illinois', 'postcode': '6220', 'country': 'United States', 'country_code': 'us'}
2908 SAN CLEMENTE, CALIFORNIA, US {'city': 'San Clemente', 'county': 'Orange County', 'state': 'California', 'postcode': '92763', 'country': 'United States', 'country_code': 'us'}
2910 LOS ALTOS HILLS, CALIFORNIA, USA {'village': 'Los Altos Hills', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
2912 BIRMINGHAM , ALABAMA, UNITED STATES {'city': 'Birmingham', 'county': 'Jefferson County', 'state': 'Alabama', 'postcode': '35202', 'country': 'United States', 'country_code': 'us'}
2913 CAMERON , MISSOURI, USA {'town': 'Cameron', 'city': 'Cameron', 'county': 'Clinton County', 'state': 'Misso

2961 ATHENS, GEORGIA, UNITED STATES  {'city': 'Athens', 'county': 'Athens-Clarke County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
2962 CAMP HILL , PENNSYLVANIA, USA  {'village': 'Camp Hill', 'county': 'Cumberland County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
2964 DALLAS, TEXAS, USA  {'city': 'Dallas', 'county': 'Dallas County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
2965 DUNCANVILLE, TEXAS, UNITED STATES {'town': 'Duncanville', 'city': 'Duncanville', 'county': 'Dallas County', 'state': 'Texas', 'postcode': '75116', 'country': 'United States', 'country_code': 'us'}
2966 FORT LAUDERDALE , FLORIDA, US {'city': 'Fort Lauderdale', 'county': 'Broward County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
2967 CHARLOTTESVILLE, VIRGINIA, US {'city': 'Charlottesville', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
2968 WILLIAMSTOWN, MASSACHUSETTS, USA

3014 OAKLAND, CALIFORNIA, UNITED STATES  {'city': 'Oakland', 'county': 'Alameda County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3015 MILFORD , MASSACHUSETTS, UNITED STATES  {'town': 'Milford', 'county': 'Worcester County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
3016 RIVERDALE, MARYLAND, UNITED STATES {'town': 'Riverdale Park', 'county': "Prince George's County", 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
3017 MIAMI , FLORIDA, US {'city': 'Miami', 'county': 'Miami-Dade County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
3018 DECATUR, GEORGIA, USA {'town': 'Decatur', 'county': 'DeKalb County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
3019 QUEENS, NEW YORK, UNITED STATES {'suburb': 'Queens', 'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
3020 REDDING CA, CALIFORNIA, USA {'city': 'Redding', 'co

3068 UTICA , NEW YORK, US {'city': 'Utica', 'county': 'Oneida County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
3069 AUGUSTA, GEORGIA, US {'city': 'Augusta', 'county': 'Richmond County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
3071 MIDLAND, TEXAS, US {'county': 'Midland County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
3072 BETHESDA, MARYLAND, USA  {'boundary': 'Bethesda', 'city': 'Bethesda', 'county': 'Montgomery County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
3073 MIDDLETOWN , PENNSYLVANIA, USA {'city': 'Middletown Township', 'county': 'Bucks County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
3074 PROVINCETOWN , MASSACHUSETTS, US {'town': 'Provincetown', 'county': 'Barnstable County', 'state': 'Massachusetts', 'postcode': '02657', 'country': 'United States', 'country_code': 'us'}
3075 MEDIA , PENNSYLVANIA, UNITED STATES {'village': 'M

3128 YAKIMA, WASHINGTON, UNITED STATES {'city': 'Yakima', 'county': 'Yakima County', 'state': 'Washington', 'postcode': '98901', 'country': 'United States', 'country_code': 'us'}
3129 BALTIMORE, MARYLAND, UNITED STATES  {'city': 'Baltimore', 'state': 'Maryland', 'postcode': '21203', 'country': 'United States', 'country_code': 'us'}
3130 IDAHO  FALLS , IDAHO, USA {'city': 'Idaho Falls', 'county': 'Bonneville County', 'state': 'Idaho', 'postcode': '83403', 'country': 'United States', 'country_code': 'us'}
3131 BOSTON AREA, MASSACHUSETTS, US {'boundary': 'Boston Harbor Islands National Recreation Area', 'city': 'Quincy', 'town': 'Winthrop', 'county': 'Suffolk County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
3132 HARTFORD , CONNECTICUT, UNITED STATES  {'city': 'Hartford', 'county': 'Hartford County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
3135 FORT PIERCE, FLORIDA, UNITED STATES {'town': 'Fort Pierce', 'county': 'Saint 

3184 ORLANDO, FLORIDA, UNITED STATES  {'city': 'Orlando', 'county': 'Orange County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
3186 O, MICHIGAN, USA {'tourism': 'O', 'road': 'West Loop', 'county': 'Oakland County', 'state': 'Michigan', 'postcode': '48356', 'country': 'United States', 'country_code': 'us'}
3187 CROWLEY , TEXAS, USA {'town': 'Crowley', 'city': 'Crowley', 'county': 'Tarrant County', 'state': 'Texas', 'postcode': '76036', 'country': 'United States', 'country_code': 'us'}
3188 FT WAYNE, INDIANA, USA {'city': 'Fort Wayne', 'county': 'Allen County', 'state': 'Indiana', 'postcode': '46802', 'country': 'United States', 'country_code': 'us'}
3190 LAS VEGAS, NEVADA, OREGON, US {'road': 'Oregon Cherry Avenue', 'city': 'Las Vegas', 'county': 'Clark County', 'state': 'Nevada', 'postcode': '89138', 'country': 'United States', 'country_code': 'us'}
3191 CHANTILLY, VIRGINIA, USA {'boundary': 'Chantilly', 'town': 'Chantilly', 'county': 'Fairfax County', 'stat

3246 BOISE, IDAHO, USA  {'city': 'Boise', 'county': 'Ada County', 'state': 'Idaho', 'postcode': '83701', 'country': 'United States', 'country_code': 'us'}
3247 NEW PALTZ, NEW YORK, USA {'village': 'New Paltz', 'municipality': 'Town of New Paltz', 'county': 'Ulster County', 'state': 'New York', 'postcode': '12561', 'country': 'United States', 'country_code': 'us'}
3249 MANDAN, NORTH DAKOTA, USA {'town': 'Mandan', 'county': 'Morton County', 'state': 'North Dakota', 'postcode': '58554', 'country': 'United States', 'country_code': 'us'}
3250 WASHINGTON DC , DISTRICT OF COLUMBIA, US  {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
3251 FORT MEADE, MARYLAND, US {'boundary': 'Fort Meade', 'village': 'Fort Meade', 'county': 'Anne Arundel County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
3252 REDMOND , WASHINGTON, UNITED STATES {'town': 'Redmond', 'county': 'King County', 'state': 'Washington', 'country': 'U

3302 EASTERN, NORTH CAROLINA, USA {'tourism': 'Blue Ridge Parkway Tent', 'road': 'South Toe River Road', 'county': 'Yancey County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
3303 BARRINGTON, ILLINOIS, US {'town': 'Barrington', 'municipality': 'Barrington Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60010', 'country': 'United States', 'country_code': 'us'}
3304 VANCOUVER, WASHINGTON, US {'city': 'Vancouver', 'county': 'Clark County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
3306 DC, DISTRICT OF COLUMBIA, UNITED STATES  {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
3307 WINNETKA, ILLINOIS, UNITED STATES {'village': 'Winnetka', 'municipality': 'New Trier Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60043', 'country': 'United States', 'country_code': 'us'}
3308 ST LOUIS, MISSOURI, USA  {'city': 'Saint Louis', 'state

3356 GRAYS HARBOR COUNTY, WASHINGTON, USA  {'county': 'Grays Harbor County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
3357 GLENDALE HEIGHTS, ILLINOIS, UNITED STATES {'town': 'Glendale Heights', 'county': 'DuPage County', 'state': 'Illinois', 'postcode': '60139', 'country': 'United States', 'country_code': 'us'}
3359 HEMET, CALIFORNIA, USA {'town': 'Hemet', 'county': 'Riverside County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3360 SIMI VALLEY , CALIFORNIA, UNITED STATES  {'city': 'Simi Valley', 'county': 'Ventura County', 'state': 'California', 'postcode': '93063-2364', 'country': 'United States', 'country_code': 'us'}
3361 MOUNTAIN VIEW, CALIFORNIA, UNITED STATES {'city': 'Mountain View', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3362 MINOT, NORTH DAKOTA, USA {'city': 'Minot', 'county': 'Ward County', 'state': 'North Dakota', 'postcode': '58702', 'country': 'U

3417 SHREWSBURY, VT, VERMONT, USA {'village': 'Shrewsbury', 'county': 'Rutland County', 'state': 'Vermont', 'postcode': '05738', 'country': 'United States', 'country_code': 'us'}
3418 LITTLETON, MASSACHUSETTS, UNITED STATES {'town': 'Littleton', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01640', 'country': 'United States', 'country_code': 'us'}
3419 MARTINSBURG, WEST VIRGINIA, US {'city': 'Martinsburg', 'county': 'Berkeley County', 'state': 'West Virginia', 'postcode': '25401', 'country': 'United States', 'country_code': 'us'}
3422 WILMINGTON , NORTH CAROLINA, USA {'city': 'Wilmington', 'county': 'New Hanover County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
3423 RESTON, VA, VIRGINIA, UNITED STATES {'locality': 'Reston', 'county': 'Fairfax County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
3424 LEESBURG VA, VIRGINIA, US {'town': 'Leesburg', 'county': 'Loudoun County', 'state': 'Virginia', 'countr

3472 CEDAR GROVE, NJ, NEW JERSEY, USA {'town': 'Cedar Grove', 'township': 'Cedar Grove', 'county': 'Essex County', 'state': 'New Jersey', 'postcode': '07009', 'country': 'United States', 'country_code': 'us'}
3473 SARATOGA SPRINGS, NEW YORK, USA {'city': 'Saratoga Springs', 'county': 'Saratoga County', 'state': 'New York', 'postcode': '12866', 'country': 'United States', 'country_code': 'us'}
3474 LONGMONT , COLORADO, USA  {'town': 'Longmont', 'county': 'Boulder County', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
3475 CORPUS CHRISTI, TEXAS, USA {'city': 'Corpus Christi', 'county': 'Nueces County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
3476 CHESTERFIELD, MI, MICHIGAN, USA {'road': 'Chesterfield', 'town': 'Waterford Township', 'county': 'Oakland County', 'state': 'Michigan', 'postcode': '48327', 'country': 'United States', 'country_code': 'us'}
3477 SAINT PETERSBURG, FLORIDA, UNITED STATES {'city': 'Saint Petersburg', 'county': 'P

3528 ELLICOTT CITY, MARYLAND, UNITED STATES {'boundary': 'Ellicott City', 'town': 'Ellicott City', 'county': 'Howard County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
3529 CHESHIRE, CONNECTICUT, USA {'town': 'Cheshire', 'county': 'New Haven County', 'state': 'Connecticut', 'postcode': '06410', 'country': 'United States', 'country_code': 'us'}
3530 CENTRAL VIRGINIA, VIRGINIA, UNITED STATES {'suburb': 'Central', 'county': 'Wood County', 'state': 'West Virginia', 'postcode': '25105', 'country': 'United States', 'country_code': 'us'}
3531 TARRYTOWN , NEW YORK, UNITED STATES {'village': 'Tarrytown', 'town': 'Town of Greenburgh', 'county': 'Westchester County', 'state': 'New York', 'postcode': '10591', 'country': 'United States', 'country_code': 'us'}
3532 ASHEVILLE, NORTH CAROLINA, UNITED STATES {'city': 'Asheville', 'county': 'Buncombe County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
3534 BOSTON METRO, MASSACHUSETTS, USA {'

3579 LOS ANGELES, CALIFORNIA, USA  {'city': 'Los Angeles', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3580 WESTMINSTER, MARYLAND, USA {'town': 'Westminster', 'county': 'Carroll County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
3582 STANFORD, CALIFORNIA, USA {'boundary': 'Stanford', 'city': 'Palo Alto', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3583 HATFIELD, PENNSYLVANIA, USA {'hamlet': 'Hatfield', 'city': 'South Union Township', 'county': 'Fayette County', 'state': 'Pennsylvania', 'postcode': '15416', 'country': 'United States', 'country_code': 'us'}
3584 DULUTH , GEORGIA, UNITED STATES {'town': 'Duluth', 'county': 'Gwinnett County', 'state': 'Georgia', 'postcode': '30096', 'country': 'United States', 'country_code': 'us'}
3585 HILLSBORO, OREGON, USA {'city': 'Hillsboro', 'county': 'Washington County', 'state': 'Oregon', 'country': 

3635 LONG BEACH , CALIFORNIA, UNITED STATES {'city': 'Long Beach', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3636 SAN RAMON , CALIFORNIA, UNITED STATES {'town': 'San Ramon', 'city': 'San Ramon', 'county': 'Contra Costa County', 'state': 'California', 'postcode': '94583', 'country': 'United States', 'country_code': 'us'}
3637 WINDHAM, MAINE, UNITED STATES {'town': 'Windham', 'county': 'Cumberland County', 'state': 'Maine', 'postcode': '04062', 'country': 'United States', 'country_code': 'us'}
3639 PORT ORCHARD, WASHINGTON, USA {'town': 'Port Orchard', 'county': 'Kitsap County', 'state': 'Washington', 'postcode': '98366', 'country': 'United States', 'country_code': 'us'}
3640 ALEXANDRIA , VIRGINIA, UNITED STATES {'city': 'Alexandria', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
3641 MERIDIAN , IDAHO, UNITED STATES {'city': 'Meridian', 'county': 'Ada County', 'state': 'Idaho', 'country': 'United Stat

3692 SAINT CLOUD, MINNESOTA, USA {'city': 'Saint Cloud', 'county': 'Stearns County', 'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
3693 RURAL, IOWA, US {'landuse': 'Pittsburg Rural Cemetery', 'hamlet': 'Pittsburg', 'county': 'Van Buren County', 'state': 'Iowa', 'country': 'United States', 'country_code': 'us'}
3695 JACKSON, TENNESSEE, UNITED STATES {'city': 'Jackson', 'county': 'Madison County', 'state': 'Tennessee', 'postcode': '38301', 'country': 'United States', 'country_code': 'us'}
3697 SCOTTSBLUFF, NEBRASKA, US {'city': 'Scottsbluff', 'county': 'Scotts Bluff County', 'state': 'Nebraska', 'postcode': '69361', 'country': 'United States', 'country_code': 'us'}
3699 ARLINGTON, TEXAS, USA {'city': 'Arlington', 'county': 'Tarrant County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
3700 FORT LAUDERDALE, FLORIDA, UNITED STATES {'city': 'Fort Lauderdale', 'county': 'Broward County', 'state': 'Florida', 'country': 'United States', 'country

3744 MCLEAN, VA, VIRGINIA, USA {'locality': 'McLean', 'hamlet': 'Brookhaven', 'county': 'Fairfax County', 'state': 'Virginia', 'postcode': '22101', 'country': 'United States', 'country_code': 'us'}
3745 MAHWAH, NEW JERSEY, UNITED STATES {'town': 'Mahwah', 'county': 'Bergen County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
3746 PARKER, COLORADO, UNITED STATES {'town': 'Parker', 'county': 'Douglas County', 'state': 'Colorado', 'postcode': '80134', 'country': 'United States', 'country_code': 'us'}
3747 LAKE FOREST PARK, WASHINGTON, UNITED STATES {'town': 'Lake Forest Park', 'county': 'King County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
3749 ATLANTA  , GEORGIA, UNITED STATES  {'city': 'Atlanta', 'county': 'Fulton County', 'state': 'Georgia', 'postcode': '30303-3506', 'country': 'United States', 'country_code': 'us'}
3750 GRAND FORKS, NORTH DAKOTA, USA  {'city': 'Grand Forks', 'county': 'Grand Forks County', 'state': 'North 

3794 REMOTE , TEXAS, US {'road': 'Remote South Parking', 'city': 'Euless', 'county': 'Tarrant County', 'state': 'Texas', 'postcode': '75261', 'country': 'United States', 'country_code': 'us'}
3795 CHERRY HILL , NEW JERSEY, UNITED STATES OF AMERICA  {'town': 'Cherry Hill Township', 'county': 'Camden County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
3797 NORTH BERGEN, NJ, NEW JERSEY, USA {'town': 'North Bergen', 'county': 'Hudson County', 'state': 'New Jersey', 'postcode': '07047-2227', 'country': 'United States', 'country_code': 'us'}
3798 ESSEX COUNTY, NEW JERSEY, USA {'county': 'Essex County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
3800 ENFIELD, NEW HAMPSHIRE, UNITED STATES {'village': 'Enfield', 'county': 'Grafton County', 'state': 'New Hampshire', 'country': 'United States', 'country_code': 'us'}
3801 MIDDLEBURG HEIGHTS, OHIO, UNITED STATES OF AMERICA {'town': 'Middleburg Heights', 'county': 'Cuyahoga County', 'state'

3853 SCHAUMBURG, ILLINOIS, US {'town': 'Schaumburg', 'municipality': 'Schaumburg Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
3854 LITTLE ROCK, ARKANSAS, US {'city': 'Little Rock', 'county': 'Pulaski County', 'state': 'Arkansas', 'postcode': '72201-1822', 'country': 'United States', 'country_code': 'us'}
3855 RICHLAND, WA, WASHINGTON, USA {'city': 'Richland', 'county': 'Benton County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
3856 CONCORD, CALIFORNIA, UNITED STATES  {'city': 'Concord', 'county': 'Contra Costa County', 'state': 'California', 'postcode': '94520', 'country': 'United States', 'country_code': 'us'}
3857 SAN FRANCISCO , CALIFORNIA, US  {'city': 'San Francisco', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3858 OFALLON, ILLINOIS, UNITED STATES {'road': 'Ofallon Street', 'village': 'Odin', 'county': 'Marion County', 'state': 'Illinois', 'postcode': '62870',

3906 PITTSBURG, KANSAS, USA {'town': 'Pittsburg', 'county': 'Crawford County', 'state': 'Kansas', 'postcode': '66762', 'country': 'United States', 'country_code': 'us'}
3907 NEWNAN, GEORGIA, UNITED STATES {'town': 'Newnan', 'county': 'Coweta County', 'state': 'Georgia', 'postcode': '30263', 'country': 'United States', 'country_code': 'us'}
3908 MICHIGAN, MICHIGAN, UNITED STATES {'railway': 'Michigan', 'house_number': '1220', 'road': 'Cass Avenue', 'city': 'Detroit', 'county': 'Wayne County', 'state': 'Michigan', 'postcode': '48226', 'country': 'United States', 'country_code': 'us'}
3910 WEST LAFAYETTE, INDIANA, US {'town': 'West Lafayette', 'county': 'Tippecanoe County', 'state': 'Indiana', 'country': 'United States', 'country_code': 'us'}
3911 MCLEAN , VIRGINIA, US {'locality': 'McLean', 'hamlet': 'Brookhaven', 'county': 'Fairfax County', 'state': 'Virginia', 'postcode': '22101', 'country': 'United States', 'country_code': 'us'}
3912 RICHMOND, TEXAS, VIRGINIA, UNITED STATES {'road': '

3960 HAMPTON, VIRGINIA, USA {'city': 'Hampton', 'state': 'Virginia', 'postcode': '23669-4019', 'country': 'United States', 'country_code': 'us'}
3961 AYER, MASSACHUSETTS, USA {'town': 'Ayer', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01432', 'country': 'United States', 'country_code': 'us'}
3962 TOLEDO, OHIO, US {'city': 'Toledo', 'county': 'Lucas County', 'state': 'Ohio', 'postcode': '43659', 'country': 'United States', 'country_code': 'us'}
3963 BARRINGTON, ILLINOIS, USA {'town': 'Barrington', 'municipality': 'Barrington Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60010', 'country': 'United States', 'country_code': 'us'}
3964 WINDSOR LOCKS, CONNECTICUT, UNITED STATES {'town': 'Windsor Locks', 'county': 'Hartford County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
3965 REMOTE, UTAH, UNITED STATES {'amenity': 'USPS Remote Encoding Center', 'house_number': '1275', 'road': '4800 West', 'city': 'Salt Lake 

4015 NEWBURYPORT, MASSACHUSETTS, US {'city': 'Newburyport', 'county': 'Essex County', 'state': 'Massachusetts', 'postcode': '01950', 'country': 'United States', 'country_code': 'us'}
4016 TAMPA, FLORIDA, USA  {'city': 'Tampa', 'county': 'Hillsborough County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
4017 OWINGS MILLS, MARYLAND, USA {'boundary': 'Owings Mills', 'town': 'Owings Mills', 'county': 'Baltimore County', 'state': 'Maryland', 'postcode': '21117', 'country': 'United States', 'country_code': 'us'}
4018 THORNTON, COLORADO, USA {'city': 'Thornton', 'county': 'Adams County', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
4019 LAWRENCEVILLE , GEORGIA, UNITED STATES {'town': 'Lawrenceville', 'county': 'Gwinnett County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
4020 RICHMOND, VIRGINIA, USA  {'city': 'Richmond', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
4021 FISH CREEK, WISCONS

4070 DELAND, FLORIDA, USA {'town': 'DeLand', 'county': 'Volusia County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
4073 REMOTE, CALIFORNIA, UNITED STATES OF AMERICA {'landuse': 'Remote Training Site Warnerspg', 'county': 'San Diego County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
4076 NEW YORK CITY, MASSACHUSETTS, US {'road': 'Massachusetts Street', 'suburb': 'Staten Island', 'city': 'New York', 'state': 'New York', 'postcode': '10307', 'country': 'United States', 'country_code': 'us'}
4077 NOT DETROIT, MICHIGAN, UNITED STATES OF AMERICA {'shop': 'Y Not Apparel', 'house_number': '2362', 'road': 'Russell Street', 'neighbourhood': 'Eastern Market', 'city': 'Detroit', 'county': 'Wayne County', 'state': 'Michigan', 'postcode': '48207', 'country': 'United States', 'country_code': 'us'}
4079 RIVER GROVE, ILLINOIS, UNITED STATES {'village': 'River Grove', 'municipality': 'Leyden Township', 'county': 'Cook County', 'state': 'Illinois

4128 DOUGLASVILLE, GEORGIA, UNITED STATES {'town': 'Douglasville', 'county': 'Douglas County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
4130 TORRANCE, CALIFORNIA, US {'city': 'Torrance', 'county': 'Los Angeles County', 'state': 'California', 'postcode': '90503', 'country': 'United States', 'country_code': 'us'}
4131 TOPEKA , KANSAS, UNITED STATES  {'city': 'Topeka', 'county': 'Shawnee County', 'state': 'Kansas', 'postcode': '66603-3758', 'country': 'United States', 'country_code': 'us'}
4132 GRINNELL, IOWA, UNITED STATES {'town': 'Grinnell', 'county': 'Poweshiek County', 'state': 'Iowa', 'postcode': '50112', 'country': 'United States', 'country_code': 'us'}
4133 COLUMBUS, OHIO, UNITED STATES OF AMERICA {'city': 'Columbus', 'county': 'Franklin County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
4134 LAKEWOOD, CO, COLORADO, UNITED STATES {'city': 'Lakewood', 'county': 'Jefferson County', 'state': 'Colorado', 'country': 'United States',

4181 NEW BRAUNFELS, TEXAS, UNITED STATES OF AMERICA  {'city': 'New Braunfels', 'county': 'Comal County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
4182 HARTFORD , CONNECTICUT, UNITED STATES {'city': 'Hartford', 'county': 'Hartford County', 'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
4183 CARLSBAD, CALIFORNIA, US {'city': 'Carlsbad', 'county': 'San Diego County', 'state': 'California', 'postcode': '92008', 'country': 'United States', 'country_code': 'us'}
4184 FORT PLAIN, NEW YORK, UNITED STATES {'village': 'Fort Plain', 'municipality': 'Town of Minden', 'county': 'Montgomery County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
4185 SILVER SPRING, MD, MARYLAND, USA {'boundary': 'Silver Spring', 'city': 'Silver Spring', 'county': 'Montgomery County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
4186 MANKATO, MINNESOTA, USA {'city': 'Mankato', 'town': 'Mankato', 'county': 'Blue Ear

4226 ST LOUIS, MISSOURI, UNITED STATES OF AMERICA {'city': 'Saint Louis', 'state': 'Missouri', 'country': 'United States', 'country_code': 'us'}
4227 ROLLING MEADOWS , ILLINOIS, UNITED STATES {'town': 'Rolling Meadows', 'municipality': 'Palatine Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60008', 'country': 'United States', 'country_code': 'us'}
4230 WICHITA, KANSAS, UNITED STATES OF AMERICA  {'city': 'Wichita', 'county': 'Sedgwick County', 'state': 'Kansas', 'postcode': '67202', 'country': 'United States', 'country_code': 'us'}
4231 LEHIGH VALLEY, PENNSYLVANIA, UNITED STATES {'highway': 'Lehigh Valley', 'road': 'Pennsylvania Turnpike Northeast Extension', 'hamlet': 'Crackersport', 'city': 'South Whitehall Township', 'county': 'Lehigh County', 'state': 'Pennsylvania', 'postcode': '18106', 'country': 'United States', 'country_code': 'us'}
4232 REDMOND, WASHINGTON, UNITED STATES OF AMERICA {'town': 'Redmond', 'county': 'King County', 'state': 'Washington', 'coun

4278 JOHNSTOWN, PENNSYLVANIA, UNITED STATES OF AMERICA {'town': 'Johnstown', 'county': 'Cambria County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
4279 SAN FRANCISCO BAY AREA, CALIFORNIA, US {'place': 'San Francisco Bay Area', 'city': 'San Francisco', 'state': 'California', 'postcode': '94110', 'country': 'United States', 'country_code': 'us'}
4280 AMITYVILLE, NEW YORK, UNITED STATES {'suburb': 'Amityville', 'village': 'Amityville', 'county': 'Suffolk County', 'state': 'New York', 'postcode': '11701', 'country': 'United States', 'country_code': 'us'}
4281 ASPEN, COLORADO, UNITED STATES {'town': 'Aspen', 'county': 'Pitkin County', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
4282 ANONYMOUS , MICHIGAN, USA {'amenity': 'Alcoholic Anonymous', 'house_number': '1557', 'road': 'Michigan Avenue', 'suburb': 'Alviso', 'city_district': 'Alviso', 'city': 'San Jose', 'county': 'Santa Clara County', 'state': 'California', 'postcode': '95002'

4329 LA QUINTA, CALIFORNIA, UNITED STATES OF AMERICA {'town': 'La Quinta', 'county': 'Riverside County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
4330 HADLEY, MASSACHUSETTS, UNITED STATES {'town': 'Hadley', 'county': 'Hampshire County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
4331 TUPELO, MISSISSIPPI, UNITED STATES  {'city': 'Tupelo', 'county': 'Lee County', 'state': 'Mississippi', 'postcode': '38804', 'country': 'United States', 'country_code': 'us'}
4333 STAUNTON, VIRGINIA, US {'city': 'Staunton', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
4336 AMESBURY, MASSACHUSETTS, USA {'city': 'Amesbury', 'county': 'Essex County', 'state': 'Massachusetts', 'postcode': '01913', 'country': 'United States', 'country_code': 'us'}
4338 MORRIS PLAINS, NEW JERSEY, UNITED STATES {'city': 'Morris Plains', 'county': 'Morris County', 'state': 'New Jersey', 'postcode': '07950', 'country': 'United States', 'countr

4381 MONMOUTH , ILLINOIS, UNITED STATES {'town': 'Monmouth', 'county': 'Warren County', 'state': 'Illinois', 'postcode': '61462', 'country': 'United States', 'country_code': 'us'}
4382 PORTLAND, OREGON, UNITED STATES OF AMERICA  {'city': 'Portland', 'county': 'Multnomah County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
4383 RENO, NEVADA, UNITED STATES  {'city': 'Reno', 'county': 'Washoe County', 'state': 'Nevada', 'country': 'United States', 'country_code': 'us'}
4384 COLUMBUS , INDIANA, OHIO, UNITED STATES {'road': 'Ohio Street', 'neighbourhood': 'East Columbus', 'town': 'Columbus', 'county': 'Bartholomew County', 'state': 'Indiana', 'postcode': '47203', 'country': 'United States', 'country_code': 'us'}
4385 SOUTHFIELD , MICHIGAN, US {'town': 'Southfield', 'county': 'Oakland County', 'state': 'Michigan', 'country': 'United States', 'country_code': 'us'}
4386 GRIMES, IOWA, USA {'town': 'Grimes', 'county': 'Polk County', 'state': 'Iowa', 'postcode': '50111', 

4428 NEWTON FALLS, OHIO, UNITED STATES {'village': 'Newton Falls', 'county': 'Trumbull County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
4429 CONCORD MA, MASSACHUSETTS, USA {'town': 'Concord', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '01742', 'country': 'United States', 'country_code': 'us'}
4430 SAUK CITY, WISCONSIN, UNITED STATES {'village': 'Sauk City', 'county': 'Sauk County', 'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
4433 NORTH CAROLINA, NORTH CAROLINA, USA {'amenity': 'United States Post Office: Southport, North Carolina', 'road': 'East Nash Street', 'village': 'Southport', 'county': 'Brunswick County', 'state': 'North Carolina', 'postcode': '28461', 'country': 'United States', 'country_code': 'us'}
4434 NEW YORK CITY, NEW YORK, AMERICA {'tourism': 'Whitney Museum of American Art', 'house_number': '99', 'road': 'Gansevoort Street', 'neighbourhood': 'Manhattan Community Board 2', 'suburb': 'Manhatta

4484 CARROLLTON, GEORGIA, UNITED STATES {'town': 'Carrollton', 'county': 'Carroll County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
4485 MANKATO , MINNESOTA, US {'city': 'Mankato', 'town': 'Mankato', 'county': 'Blue Earth County', 'state': 'Minnesota', 'postcode': '56001', 'country': 'United States', 'country_code': 'us'}
4487 BRUNSWICK, MAINE, UNITED STATES {'town': 'Brunswick', 'county': 'Cumberland County', 'state': 'Maine', 'postcode': '04011', 'country': 'United States', 'country_code': 'us'}
4489 GOLDEN, COLORADO, UNITED STATES OF AMERICA {'town': 'Golden', 'county': 'Jefferson County', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
4490 BOULDER , COLORADO, USA {'city': 'Boulder', 'county': 'Boulder County', 'state': 'Colorado', 'postcode': '80306', 'country': 'United States', 'country_code': 'us'}
4491 ALBANY , NEW YORK, UNITED STATES {'city': 'Albany', 'county': 'Albany County', 'state': 'New York', 'country': 'United States'

4542 CASPER, WYOMING, US {'city': 'Casper', 'county': 'Natrona County', 'state': 'Wyoming', 'postcode': '82601', 'country': 'United States', 'country_code': 'us'}
4543 GRAPEVINE, TEXAS, USA {'town': 'Grapevine', 'city': 'Grapevine', 'county': 'Tarrant County', 'state': 'Texas', 'postcode': '76051', 'country': 'United States', 'country_code': 'us'}
4545 NARNIA, TENNESSEE, UNITED STATES {'road': 'Narnia Loop', 'hamlet': 'Watts Bar Estates', 'county': 'Rhea County', 'state': 'Tennessee', 'postcode': '27381', 'country': 'United States', 'country_code': 'us'}
4546 EDMONDS, WASHINGTON, USA {'town': 'Edmonds', 'county': 'Snohomish County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
4547 DENVER CO, COLORADO, USA {'city': 'Denver', 'state': 'Colorado', 'country': 'United States', 'country_code': 'us'}
4548 RENTON , WASHINGTON, USA {'town': 'Renton', 'county': 'King County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
4550 IRVING , TEXAS

4591 MARION, IOWA, UNITED STATES {'county': 'Marion County', 'state': 'Iowa', 'country': 'United States', 'country_code': 'us'}
4592 CUPERTINO, CA, CALIFORNIA, UNITED STATES {'city': 'Cupertino', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
4594 NYC, NEW JERSEY, USA {'highway': 'Newton Park and Ride - Lakeland Bus to NYC', 'road': 'South Park Drive', 'city': 'Hampton Township', 'county': 'Sussex County', 'state': 'New Jersey', 'postcode': '07460', 'country': 'United States', 'country_code': 'us'}
4595 ARROYO GRANDE, CALIFORNIA, USA  {'town': 'Arroyo Grande', 'city': 'Arroyo Grande', 'county': 'San Luis Obispo County', 'state': 'California', 'postcode': '93420-2419', 'country': 'United States', 'country_code': 'us'}
4596 DURHAM , NORTH CAROLINA, USA {'city': 'Durham', 'county': 'Durham County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
4597 ST PETERSBURG , FLORIDA, UNITED STATES {'city': 'Sain

4644 PISCATAWAY, NJ, NEW JERSEY, UNITED STATES OF AMERICA {'town': 'Piscataway Township', 'county': 'Middlesex County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
4645 QUEEN CREEK, ARIZONA, USA {'town': 'Queen Creek', 'county': 'Maricopa County', 'state': 'Arizona', 'country': 'United States', 'country_code': 'us'}
4646 KATY, TEXAS, USA {'town': 'Katy', 'city': 'Katy', 'county': 'Fort Bend County', 'state': 'Texas', 'postcode': '77493', 'country': 'United States', 'country_code': 'us'}
4647 PORT ST LUCIE, FLORIDA, USA {'city': 'Port Saint Lucie', 'county': 'Saint Lucie County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
4648 SPRINGFIELD, MASSACHUSETTS, UNITED STATES {'city': 'Springfield', 'county': 'Hampden County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
4649 HORSHAM , PENNSYLVANIA, USA  {'boundary': 'Horsham', 'town': 'Horsham', 'city': 'Horsham Township', 'county': 'Montgomery County', 'sta

4693 DICKINSON, NORTH DAKOTA, UNITED STATES {'city': 'Dickinson', 'county': 'Stark County', 'state': 'North Dakota', 'postcode': '58602', 'country': 'United States', 'country_code': 'us'}
4694 ATTLEBORO, MASSACHUSETTS, USA {'city': 'Attleboro', 'county': 'Bristol County', 'state': 'Massachusetts', 'postcode': '02703', 'country': 'United States', 'country_code': 'us'}
4695 MERIDIAN, IDAHO, UNITED STATES {'city': 'Meridian', 'county': 'Ada County', 'state': 'Idaho', 'country': 'United States', 'country_code': 'us'}
4696 GAINESVILLE, TEXAS, UNITED STATES {'town': 'Gainesville', 'county': 'Cooke County', 'state': 'Texas', 'postcode': '76240', 'country': 'United States', 'country_code': 'us'}
4697 DRAPER, UTAH, US {'town': 'Draper', 'city': 'Draper', 'county': 'Salt Lake County', 'state': 'Utah', 'postcode': '84020', 'country': 'United States', 'country_code': 'us'}
4698 POTSDAM, NEW YORK, US {'village': 'Potsdam', 'municipality': 'Town of Potsdam', 'county': 'Saint Lawrence County', 'state

4748 SCHAUMBURG , ILLINOIS, USA {'town': 'Schaumburg', 'municipality': 'Schaumburg Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
4749 ALEXANDRIA, VIRGINIA, UNITED STATES  {'city': 'Alexandria', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
4750 NASHVILLE , TENNESSEE, US  {'city': 'Nashville', 'county': 'Davidson County', 'state': 'Tennessee', 'country': 'United States', 'country_code': 'us'}
4751 NEWBURGH, NEW YORK, US {'city': 'Newburgh', 'county': 'Orange County', 'state': 'New York', 'postcode': '12550', 'country': 'United States', 'country_code': 'us'}
4752 CHERRY HILL, NEW JERSEY, USA {'town': 'Cherry Hill Township', 'county': 'Camden County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
4754 RICHMOND, VA, VIRGINIA, USA {'city': 'Richmond', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
4756 WASHINGTON, DC, DISTRICT OF COLUMBIA, AMERICA {'office

4800 LAKE ORION, MICHIGAN, UNITED STATES {'village': 'Lake Orion', 'county': 'Oakland County', 'state': 'Michigan', 'postcode': '48362', 'country': 'United States', 'country_code': 'us'}
4801 ST CHARLES, MISSOURI, USA {'county': 'Saint Charles County', 'state': 'Missouri', 'country': 'United States', 'country_code': 'us'}
4802 LENEXA, KANSAS, USA  {'city': 'Lenexa', 'county': 'Johnson County', 'state': 'Kansas', 'country': 'United States', 'country_code': 'us'}
4803 CAMARILLO, CALIFORNIA, USA {'town': 'Camarillo', 'county': 'Ventura County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
4805 MISSOURI, MISSOURI, US {'tourism': 'Airline History Museum', 'house_number': '201', 'road': 'Northwest Lou Holland Drive', 'neighbourhood': 'Harlem', 'city': 'Kansas City', 'county': 'Clay County', 'state': 'Missouri', 'postcode': '64116', 'country': 'United States', 'country_code': 'us'}
4806 OXFORD, OHIO, UNITED STATES {'town': 'Oxford', 'municipality': 'Oxford Township

4850 GLOUCESTER, VIRGINIA, UNITED STATES {'county': 'Gloucester', 'state': 'Virginia', 'postcode': '23061', 'country': 'United States', 'country_code': 'us'}
4851 HARRISBURG , PENNSYLVANIA, US {'city': 'Harrisburg', 'county': 'Dauphin County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
4852 MENLO PARK, CALIFORNIA, US {'town': 'Menlo Park', 'county': 'San Mateo County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
4853 HARRODSBURG, KENTUCKY, USA {'town': 'Harrodsburg', 'village': 'Harrodsburg', 'county': 'Mercer County', 'state': 'Kentucky', 'postcode': '40330', 'country': 'United States', 'country_code': 'us'}
4854 BRIDGEWATER , NEW JERSEY, USA {'railway': 'Bridgewater', 'road': 'Main Street', 'township': 'Bridgewater Township', 'county': 'Somerset County', 'state': 'New Jersey', 'postcode': '08805', 'country': 'United States', 'country_code': 'us'}
4855 LAWRENCE, KANSAS, US {'city': 'Lawrence', 'county': 'Douglas County', 'st

4906 ROSEMOUNT, MINNESOTA, UNITED STATES OF AMERICA {'town': 'Rosemount', 'city': 'Rosemount', 'county': 'Dakota County', 'state': 'Minnesota', 'postcode': '55068-3106', 'country': 'United States', 'country_code': 'us'}
4907 MT PROSPECT, ILLINOIS, USA {'town': 'Mount Prospect', 'municipality': 'Wheeling Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
4908 CHESTNUT HILL, MASSACHUSETTS, US {'suburb': 'Chestnut Hill', 'city': 'Newton', 'county': 'Middlesex County', 'state': 'Massachusetts', 'postcode': '02435', 'country': 'United States', 'country_code': 'us'}
4909 ROCKFORD, ILLINOIS, US {'city': 'Rockford', 'municipality': 'Rockford Township', 'county': 'Winnebago County', 'state': 'Illinois', 'postcode': '61104', 'country': 'United States', 'country_code': 'us'}
4910 IPSWICH, MASSACHUSETTS, UNITED STATES {'town': 'Ipswich', 'county': 'Essex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
4911

4958 MCCOMB, OHIO, UNITED STATES {'village': 'McComb', 'county': 'Hancock County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
4960 GREATER PORTLAND , MAINE, UNITED STATES {'amenity': 'Unity of Greater Portland Church', 'road': 'Gay Street', 'neighbourhood': 'Rosemont', 'city': 'Portland', 'county': 'Cumberland County', 'state': 'Maine', 'postcode': '04103', 'country': 'United States', 'country_code': 'us'}
4964 LARAMIE, WYOMING, USA  {'city': 'Laramie', 'county': 'Albany County', 'state': 'Wyoming', 'postcode': '82070', 'country': 'United States', 'country_code': 'us'}
4965 BLOOMINGTON, ILLINOIS, USA  {'city': 'Bloomington', 'county': 'McLean County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
4966 BROOKLYN , NEW YORK, USA {'suburb': 'Brooklyn', 'city_district': 'Kings County', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
4967 NEW YORK, NY, NEW YORK, US {'city': 'New York', 'state': 'New York', 'country': 'Un

5014 RALEIGH , NORTH CAROLINA, USA  {'city': 'Raleigh', 'county': 'Wake County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
5016 NATICK, MASSACHUSETTS, US {'town': 'Natick', 'county': 'Middlesex County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
5017 RALEIGH, NORTH DAKOTA, UNITED STATES {'hamlet': 'Raleigh', 'county': 'Grant County', 'state': 'North Dakota', 'country': 'United States', 'country_code': 'us'}
5018 WASINGTON , DISTRICT OF COLUMBIA, USA {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
5019 QUAKERTOWN, PENNSYLVANIA, UNITED STATES {'village': 'Quakertown', 'county': 'Bucks County', 'state': 'Pennsylvania', 'postcode': '18951', 'country': 'United States', 'country_code': 'us'}
5020 LEADVILLE, COLORADO, UNITED STATES  {'town': 'Leadville', 'county': 'Lake County', 'state': 'Colorado', 'postcode': '80461', 'country': 'United States', 'country_code': 'us'}

5071 KANSAS CITY , KANSAS, US {'city': 'Downtown Kansas City', 'county': 'Jackson County', 'state': 'Missouri', 'postcode': '64106-2303', 'country': 'United States', 'country_code': 'us'}
5072 MILLVILLE, NEW JERSEY, UNITED STATES {'town': 'Millville', 'county': 'Cumberland County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
5074 HARRISON, ARKANSAS, USA {'town': 'Harrison', 'city': 'Harrison', 'county': 'Boone County', 'state': 'Arkansas', 'postcode': '72601', 'country': 'United States', 'country_code': 'us'}
5075 ORMOND BEACH, FLORIDA, USA {'town': 'Ormond Beach', 'city': 'Ormond Beach', 'county': 'Volusia County', 'state': 'Florida', 'postcode': '32176-8105', 'country': 'United States', 'country_code': 'us'}
5076 LAPLACE, LOUISIANA, USA {'locality': 'LaPlace', 'county': 'St. John the Baptist Parish', 'state': 'Louisiana', 'postcode': '70068', 'country': 'United States', 'country_code': 'us'}
5077 CARROLLTON, TEXAS, UNITED STATES {'town': 'Carrollton', 'ci

5125 ASHBURN , VIRGINIA, USA {'boundary': 'Ashburn', 'town': 'Ashburn', 'county': 'Loudoun County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
5126 NA, NEW HAMPSHIRE, UNITED STATES  {'road': 'New Hampshire', 'suburb': 'Walnut', 'city': 'Irvine', 'county': 'Orange County', 'state': 'California', 'postcode': '92604-2239', 'country': 'United States', 'country_code': 'us'}
5128 SPRINGFIELD , MASSACHUSETTS, UNITED STATES {'city': 'Springfield', 'county': 'Hampden County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
5129 LYNNWOOD , WASHINGTON, USA {'town': 'Lynnwood', 'county': 'Snohomish County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
5130 WILKES BARRE, PENNSYLVANIA, USA {'city': 'Wilkes-Barre', 'county': 'Luzerne County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
5131 WILMINGTON , NORTH CAROLINA, UNITED STATES  {'city': 'Wilmington', 'county': 'New Hanover County',

5177 FRANKFORT , KENTUCKY, UNITED STATES OF AMERICA {'city': 'Frankfort', 'county': 'Franklin County', 'state': 'Kentucky', 'postcode': '40601', 'country': 'United States', 'country_code': 'us'}
5178 NEENAH, WISCONSIN, UNITED STATES {'town': 'Neenah', 'county': 'Winnebago County', 'state': 'Wisconsin', 'postcode': '54956', 'country': 'United States', 'country_code': 'us'}
5180 MAITLAND, FLORIDA, UNITED STATES {'suburb': 'Maitland', 'county': 'Orange County', 'state': 'Florida', 'postcode': '32751', 'country': 'United States', 'country_code': 'us'}
5181 WEST PALM BEACH , FLORIDA, US {'city': 'West Palm Beach', 'county': 'Palm Beach County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
5182 LAS VEGAS , NEVADA, USA  {'city': 'Las Vegas', 'county': 'Clark County', 'state': 'Nevada', 'country': 'United States', 'country_code': 'us'}
5183 HOUSTON , TEXAS, USA  {'city': 'Houston', 'county': 'Harris County', 'state': 'Texas', 'country': 'United States', 'country_code':

5234 PLEASANT GROVE, UTAH, USA {'town': 'Pleasant Grove', 'city': 'Pleasant Grove', 'county': 'Utah County', 'state': 'Utah', 'postcode': '84062', 'country': 'United States', 'country_code': 'us'}
5235 MENTOR, OHIO, OHIO, US {'city': 'Mentor', 'town': 'Mentor', 'county': 'Lake County', 'state': 'Ohio', 'postcode': '44060', 'country': 'United States', 'country_code': 'us'}
5236 TELL CITY, INDIANA, USA {'village': 'Tell City', 'county': 'Perry County', 'state': 'Indiana', 'country': 'United States', 'country_code': 'us'}
5237 FULTON, MISSISSIPPI, USA {'village': 'Fulton', 'county': 'Itawamba County', 'state': 'Mississippi', 'postcode': '38843', 'country': 'United States', 'country_code': 'us'}
5238 DEKALB, ILLINOIS, USA {'county': 'DeKalb County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
5239 BURLINGTON, KANSAS, UNITED STATES {'town': 'Burlington', 'county': 'Coffey County', 'state': 'Kansas', 'postcode': '66839', 'country': 'United States', 'country_code': 

5285 BOYNTON BEACH, FLORIDA, USA {'city': 'Boynton Beach', 'county': 'Palm Beach County', 'state': 'Florida', 'postcode': '33435', 'country': 'United States', 'country_code': 'us'}
5286 LYNDHURST, NEW JERSEY, USA {'town': 'Lyndhurst', 'county': 'Bergen County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
5288 FRANKLIN , INDIANA, US {'town': 'Franklin', 'county': 'Johnson County', 'state': 'Indiana', 'postcode': '46131', 'country': 'United States', 'country_code': 'us'}
5289 BENSENVILLE, ILLINOIS, UNITED STATES  {'town': 'Bensenville', 'county': 'DuPage County', 'state': 'Illinois', 'postcode': '60106', 'country': 'United States', 'country_code': 'us'}
5291 FREDERICKSBURG , VIRGINIA, USA  {'town': 'Fredericksburg', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
5292 TEMPE, ARIZONA, USA  {'city': 'Tempe', 'county': 'Maricopa County', 'state': 'Arizona', 'postcode': '85281', 'country': 'United States', 'country_code': 'us'}
5293 KALAMAZ

5336 BLUFFDALE, UTAH, USA {'town': 'Bluffdale', 'county': 'Salt Lake County', 'state': 'Utah', 'postcode': '84065', 'country': 'United States', 'country_code': 'us'}
5337 DECATUR, ALABAMA, USA {'city': 'Decatur', 'town': 'Decatur', 'county': 'Morgan County', 'state': 'Alabama', 'postcode': '35602', 'country': 'United States', 'country_code': 'us'}
5338 CENTERVILLE , UTAH, UNITED STATES  {'town': 'Centerville', 'county': 'Davis County', 'state': 'Utah', 'postcode': '84014', 'country': 'United States', 'country_code': 'us'}
5339 DALLAS , TEXAS, USA  {'city': 'Dallas', 'county': 'Dallas County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
5340 SCHAUMBURG, ILLINOIS, USA {'town': 'Schaumburg', 'municipality': 'Schaumburg Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
5341 PORTLAND , MAINE, UNITED STATES {'city': 'Portland', 'county': 'Cumberland County', 'state': 'Maine', 'country': 'United States', 'country

5389 CROSSVILLE, TENNESSEE, UNITED STATES {'town': 'Crossville', 'county': 'Cumberland County', 'state': 'Tennessee', 'postcode': '37855', 'country': 'United States', 'country_code': 'us'}
5390 ROYERSFORD, PENNSYLVANIA, UNITED STATES {'borough': 'Royersford', 'county': 'Montgomery County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
5391 RIDGEFIELD PARK, NEW JERSEY, US {'town': 'Ridgefield Park', 'village': 'Ridgefield Park', 'county': 'Bergen County', 'state': 'New Jersey', 'postcode': '07660', 'country': 'United States', 'country_code': 'us'}
5392 SKIP, VIRGINIA, UNITED STATES OF AMERICA {'road': 'Skip Jack Drive', 'hamlet': 'Willis Wharf', 'county': 'Northampton County', 'state': 'Virginia', 'postcode': '23486', 'country': 'United States', 'country_code': 'us'}
5393 CANTON, OHIO, USA {'city': 'Canton', 'county': 'Stark County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
5394 ANKENY, IOWA, US {'town': 'Ankeny', 'county': 'Polk Co

5444 GREENSBURG, PENNSYLVANIA, USA  {'city': 'Greensburg', 'county': 'Westmoreland County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
5445 GREENFIELD, MASSACHUSETTS, USA {'city': 'Greenfield', 'county': 'Franklin County', 'state': 'Massachusetts', 'postcode': '01301', 'country': 'United States', 'country_code': 'us'}
5446 UNIVERSITY CITY, MISSOURI, UNITED STATES OF AMERICA {'town': 'University City', 'county': 'Saint Louis County', 'state': 'Missouri', 'postcode': '63130', 'country': 'United States', 'country_code': 'us'}
5447 HYATTSVILLE, MARYLAND, USA {'town': 'Hyattsville', 'county': "Prince George's County", 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
5451 REDLANDS, CALIFORNIA, US {'town': 'Redlands', 'county': 'San Bernardino County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
5452 CHARLESTOWN BOSTON, MASSACHUSETTS, USA {'suburb': 'Charlestown', 'city': 'Boston', 'county': 'Suffolk County', '

5493 ATLANTA, GA , GEORGIA, USA {'city': 'Atlanta', 'county': 'Fulton County', 'state': 'Georgia', 'postcode': '30303-3506', 'country': 'United States', 'country_code': 'us'}
5494 CORTLAND, NEW YORK, UNITED STATES {'town': 'Cortland', 'municipality': 'Cortlandville Town', 'county': 'Cortland County', 'state': 'New York', 'postcode': '13045', 'country': 'United States', 'country_code': 'us'}
5495 ORANGE, MASSACHUSETTS, UNITED STATES {'town': 'Orange', 'county': 'Franklin County', 'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
5497 NEW LENOX, ILLINOIS, USA {'town': 'New Lenox', 'village': 'New Lenox', 'county': 'Will County', 'state': 'Illinois', 'postcode': '60451', 'country': 'United States', 'country_code': 'us'}
5498 KING OF PRUSSIA, PENNSYLVANIA, UNITED STATES OF AMERICA {'boundary': 'King of Prussia', 'town': 'King of Prussia', 'city': 'Upper Merion Township', 'county': 'Montgomery County', 'state': 'Pennsylvania', 'country': 'United States', 'country_c

5544 MARYSVILLE, WASHINGTON, USA {'town': 'Marysville', 'county': 'Snohomish County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
5545 SOUTH SAN FRANCISCO, CALIFORNIA, US {'city': 'South San Francisco', 'county': 'San Mateo County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
5546 SAVANNAH, GEORGIA, UNITED STATES OF AMERICA {'city': 'Savannah', 'county': 'Chatham County', 'state': 'Georgia', 'country': 'United States', 'country_code': 'us'}
5547 MIAMI , FLORIDA, UNITED STATES  {'city': 'Miami', 'county': 'Miami-Dade County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
5548 COLLEGE STATION, TEXAS, US  {'city': 'College Station', 'county': 'Brazos County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
5549 GIG HARBOR, WASHINGTON, UNITED STATES {'town': 'Gig Harbor', 'county': 'Pierce County', 'state': 'Washington', 'postcode': '98335', 'country': 'United States', 'country_code': 'us'

5592 TIGARD, OREGON, USA {'city': 'Tigard', 'county': 'Washington County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
5593 MT WASHINGTON, KENTUCKY, USA {'town': 'Mount Washington', 'city': 'Mount Washington', 'county': 'Bullitt County', 'state': 'Kentucky', 'postcode': '40047', 'country': 'United States', 'country_code': 'us'}
5594 TUPELO , MISSISSIPPI, USA {'city': 'Tupelo', 'county': 'Lee County', 'state': 'Mississippi', 'postcode': '38804', 'country': 'United States', 'country_code': 'us'}
5595 LUSBY, MARYLAND, USA {'boundary': 'Lusby', 'village': 'Lusby', 'county': 'Calvert County', 'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
5596 PORTLAND OR, OREGON, USA {'city': 'Portland', 'county': 'Multnomah County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
5597 CHICAGO, IL, ILLINOIS, UNITED STATES OF AMERICA {'city': 'Chicago', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_cod

5644 SHEBOYGAN , WISCONSIN, US {'city': 'Sheboygan', 'county': 'Sheboygan County', 'state': 'Wisconsin', 'postcode': '53081', 'country': 'United States', 'country_code': 'us'}
5645 CAMDEN, SOUTH CAROLINA, USA {'town': 'Camden', 'county': 'Kershaw County', 'state': 'South Carolina', 'country': 'United States', 'country_code': 'us'}
5647 REMOTE, VIRGINIA, UNITED STATES {'road': 'Remote Delivery Facility Secure Access Lane', 'suburb': 'Pentagon City', 'city': 'Arlington', 'county': 'Arlington County', 'state': 'Virginia', 'postcode': '20301', 'country': 'United States', 'country_code': 'us'}
5648 NAPERVILLE IL, ILLINOIS, USA {'city': 'Naperville', 'county': 'DuPage County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
5649 CALIFORNIA, MARYLAND, UNITED STATES {'hamlet': 'California', 'town': 'Lexington Park', 'county': "Saint Mary's County", 'state': 'Maryland', 'postcode': '20619-2488', 'country': 'United States', 'country_code': 'us'}
5650 JONESBORO, ARKANSAS, U

5699 CAPE GIRARDEAU, MISSOURI, US {'city': 'Cape Girardeau', 'county': 'Cape Girardeau County', 'state': 'Missouri', 'postcode': '63703', 'country': 'United States', 'country_code': 'us'}
5700 BALTIMORE AREA, MARYLAND, USA {'amenity': 'Randallstown Area Branch Baltimore County Public Library', 'house_number': '8604', 'road': 'Liberty Road', 'town': 'Randallstown', 'county': 'Baltimore County', 'state': 'Maryland', 'postcode': '21133', 'country': 'United States', 'country_code': 'us'}
5701 KEY WEST, FLORIDA, USA {'town': 'Key West', 'county': 'Monroe County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
5702 ALAMEDA, CALIFORNIA, UNITED STATES  {'county': 'Alameda County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
5703 CENTREVILLE, VIRGINIA, US {'boundary': 'Centreville', 'town': 'Centreville', 'county': 'Fairfax County', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
5704 DECATUR, ILLINOIS, USA {'town': 'Dec

5752 WARWICK , RHODE ISLAND, UNITED STATES {'suburb': 'Warwick', 'county': 'Kent County', 'state': 'Rhode Island', 'country': 'United States', 'country_code': 'us'}
5753 LOS ANGELES AREA, CALIFORNIA, UNITED STATES {'landuse': 'Los Angeles Air Force Base (Fort Macarthur Housing Area)', 'suburb': 'San Pedro', 'city': 'Los Angeles', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
5754 DEERFIELD BEACH, FLORIDA, UNITED STATES {'city': 'Deerfield Beach', 'county': 'Broward County', 'state': 'Florida', 'postcode': '33441', 'country': 'United States', 'country_code': 'us'}
5755 SPRINGFIELD , MISSOURI, USA  {'city': 'Springfield', 'county': 'Greene County', 'state': 'Missouri', 'country': 'United States', 'country_code': 'us'}
5756 JUNEAU, ALASKA, USA {'city': 'Juneau', 'state': 'Alaska', 'country': 'United States', 'country_code': 'us'}
5757 AUGUSTA , MICHIGAN, UNITED STATES {'village': 'Augusta', 'municipality': 'Ross Township', 'county

5813 SUN PRAIRIE, WISCONSIN, UNITED STATES {'city': 'Sun Prairie', 'county': 'Dane County', 'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
5815 RIDGEFIELD, CONNECTICUT, USA {'town': 'Ridgefield', 'county': 'Fairfield County', 'state': 'Connecticut', 'postcode': '06877', 'country': 'United States', 'country_code': 'us'}
5816 ST JOSEPH, MICHIGAN, USA {'county': 'Saint Joseph County', 'state': 'Michigan', 'country': 'United States', 'country_code': 'us'}
5817 VESTAL, NEW YORK, UNITED STATES {'town': 'Vestal', 'municipality': 'Vestal Town', 'county': 'Broome County', 'state': 'New York', 'postcode': '13850-1542', 'country': 'United States', 'country_code': 'us'}
5818 DISTRICT OF COLUMBIA , DISTRICT OF COLUMBIA, UNITED STATES  {'amenity': 'University of California Washington Center', 'house_number': '1608', 'road': 'Rhode Island Avenue Northwest', 'city': 'Washington', 'state': 'District of Columbia', 'postcode': '20036', 'country': 'United States', 'country_code': 

5871 SWEET SPRINGS, MISSOURI, USA  {'village': 'Sweet Springs', 'county': 'Saline County', 'state': 'Missouri', 'postcode': '65351', 'country': 'United States', 'country_code': 'us'}
5872 CHARLOTTESVILLE, VIRGINIA, USA  {'city': 'Charlottesville', 'state': 'Virginia', 'country': 'United States', 'country_code': 'us'}
5873 ELKTON, VA, OHIO, UNITED STATES {'hamlet': 'Elkton', 'county': 'Columbiana County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
5874 WASHINGTON, DC , DISTRICT OF COLUMBIA, UNITED STATES  {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
5875 FAIRBURY, NEBRASKA, UNITED STATES {'town': 'Fairbury', 'county': 'Jefferson County', 'state': 'Nebraska', 'country': 'United States', 'country_code': 'us'}
5877 WARNER ROBINS , GEORGIA, USA  {'city': 'Warner Robins', 'county': 'Houston County', 'state': 'Georgia', 'postcode': '31098', 'country': 'United States', 'country_code': 'us'}
5878 ROOTSTOWN, OHI

5923 BISMARCK, NORTH DAKOTA, USA {'city': 'Bismarck', 'county': 'Burleigh County', 'state': 'North Dakota', 'country': 'United States', 'country_code': 'us'}
5924 JACKSONVILLE , NORTH CAROLINA, UNITED STATES {'city': 'Jacksonville', 'county': 'Onslow County', 'state': 'North Carolina', 'postcode': '28540', 'country': 'United States', 'country_code': 'us'}
5926 SALMON, IDAHO, UNITED STATES {'town': 'Salmon', 'county': 'Lemhi County', 'state': 'Idaho', 'postcode': '83467', 'country': 'United States', 'country_code': 'us'}
5927 SALT LAKE CITY , UTAH, UNITED STATES OF AMERICA  {'city': 'Salt Lake City', 'county': 'Salt Lake County', 'state': 'Utah', 'postcode': '84139', 'country': 'United States', 'country_code': 'us'}
5928 CARLSBAD, CALIFORNIA, USA {'city': 'Carlsbad', 'county': 'San Diego County', 'state': 'California', 'postcode': '92008', 'country': 'United States', 'country_code': 'us'}
5930 WESTFIELD, MASSACHUSETTS, UNITED STATES {'city': 'Westfield', 'county': 'Hampden County', 'sta

5981 CUPERTINO, CALIFORNIA, UNITED STATES OF AMERICA {'city': 'Cupertino', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
5982 GLOUCESTER , NEW JERSEY, USA {'county': 'Gloucester County', 'state': 'New Jersey', 'country': 'United States', 'country_code': 'us'}
5983 RAPID CITY , SOUTH DAKOTA, USA {'city': 'Rapid City', 'county': 'Pennington County', 'state': 'South Dakota', 'country': 'United States', 'country_code': 'us'}
5984 LOMPOC, CALIFORNIA, US {'town': 'Lompoc', 'county': 'Santa Barbara County', 'state': 'California', 'postcode': '93436', 'country': 'United States', 'country_code': 'us'}
5985 SEABROOK, NEW HAMPSHIRE, UNITED STATES {'city': 'Seabrook', 'county': 'Rockingham County', 'state': 'New Hampshire', 'postcode': '03874', 'country': 'United States', 'country_code': 'us'}
5986 BRENTWOOD, TENNESSEE, US {'town': 'Brentwood', 'county': 'Williamson County', 'state': 'Tennessee', 'postcode': '37027', 'country': 'United Sta

6032 MADISON HEIGHTS, MICHIGAN, USA {'town': 'Madison Heights', 'county': 'Oakland County', 'state': 'Michigan', 'postcode': '48071', 'country': 'United States', 'country_code': 'us'}
6033 HAZLET, NEW JERSEY, US {'town': 'Hazlet', 'township': 'Hazlet Township', 'county': 'Monmouth County', 'state': 'New Jersey', 'postcode': '07730', 'country': 'United States', 'country_code': 'us'}
6034 MADISON, MISSISSIPPI, US {'town': 'Madison', 'county': 'Madison County', 'state': 'Mississippi', 'country': 'United States', 'country_code': 'us'}
6035 MARYVILLE , ILLINOIS, UNITED STATES {'village': 'Maryville', 'county': 'Madison County', 'state': 'Illinois', 'postcode': '62062', 'country': 'United States', 'country_code': 'us'}
6036 MORENCI, ARIZONA, USA {'town': 'Morenci', 'county': 'Greenlee County', 'state': 'Arizona', 'country': 'United States', 'country_code': 'us'}
6037 MOON TWP PA, PENNSYLVANIA, UNITED STATES {'town': 'Moon Township', 'county': 'Allegheny County', 'state': 'Pennsylvania', 'cou

6089 CHICAGO, ILLINOIS, ISA {'road': 'Isa Avenue', 'town': 'Chicago Heights', 'municipality': 'Bloom Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60411', 'country': 'United States', 'country_code': 'us'}
6090 RICHARDSON, TEXAS, USA  {'city': 'Richardson', 'county': 'Dallas County', 'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
6091 LONG BEACH, NEW YORK, USA {'town': 'Long Beach', 'city': 'Long Beach', 'county': 'Nassau County', 'state': 'New York', 'postcode': '11561', 'country': 'United States', 'country_code': 'us'}
6092 MIAMI , FLORIDA, USA {'city': 'Miami', 'county': 'Miami-Dade County', 'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
6093 NOLA, LOUISIANA, USA {'city': 'New Orleans', 'county': 'Orleans Parish', 'state': 'Louisiana', 'postcode': '70116:70119', 'country': 'United States', 'country_code': 'us'}
6094 CHARLTON, MASSACHUSETTS, USA {'town': 'Charlton', 'county': 'Worcester County', 'state': 'Massachusett

6140 CERES, CALIFORNIA, UNITED STATES {'town': 'Ceres', 'county': 'Stanislaus County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
6141 BOUNTIFUL, UTAH, US {'town': 'Bountiful', 'county': 'Davis County', 'state': 'Utah', 'postcode': '84010', 'country': 'United States', 'country_code': 'us'}
6142 REMOTE, MISSOURI, UNITED STATES {'highway': 'Remote Control Car Track', 'road': 'Parkside Drive', 'city': 'Columbia', 'county': 'Boone County', 'state': 'Missouri', 'postcode': '65202', 'country': 'United States', 'country_code': 'us'}
6144 MURRAY, UTAH, UNITED STATES {'town': 'Murray', 'city': 'Murray', 'county': 'Salt Lake County', 'state': 'Utah', 'postcode': '84107', 'country': 'United States', 'country_code': 'us'}
6145 SADDLEBROOK, NEW JERSEY, USA {'road': 'Saddlebrook Drive', 'township': 'Evesham Township', 'county': 'Burlington County', 'state': 'New Jersey', 'postcode': '08053', 'country': 'United States', 'country_code': 'us'}
6146 STOWE, VERMONT, USA {'to

6193 COLUMBUS , OHIO, USA  {'city': 'Columbus', 'county': 'Franklin County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
6194 KENNEDY SPACE CENTER, FLORIDA, USA {'aeroway': 'John F. Kennedy Space Center', 'county': 'Brevard County', 'state': 'Florida', 'postcode': '32899', 'country': 'United States', 'country_code': 'us'}
6195 PORTLAND , OREGON, UNITED STATES OF AMERICA  {'city': 'Portland', 'county': 'Multnomah County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
6196 STERLING HEIGHTS, MICHIGAN, USA {'city': 'Sterling Heights', 'town': 'Sterling Heights', 'county': 'Macomb County', 'state': 'Michigan', 'postcode': '48313-4615', 'country': 'United States', 'country_code': 'us'}
6197 REMOTE, ILLINOIS, USA  {'building': 'Remote Parking ATS Station (Closed)', 'road': 'Coffey Road', 'suburb': "O'Hare", 'city': 'Chicago', 'municipality': 'Jefferson Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60666', 'country': 'United

6249 PALATINE, ILLINOIS, UNITED STATES {'town': 'Palatine', 'municipality': 'Palatine Township', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
6250 OCONOMOWOC, WISCONSIN, USA {'town': 'Oconomowoc', 'county': 'Waukesha County', 'state': 'Wisconsin', 'postcode': '53066', 'country': 'United States', 'country_code': 'us'}
6252 WILLISTON, NORTH DAKOTA, USA {'city': 'Williston', 'county': 'Williams County', 'state': 'North Dakota', 'postcode': '58801', 'country': 'United States', 'country_code': 'us'}
6253 NEW BEDFORD, MASSACHUSETTS, USA {'city': 'New Bedford', 'county': 'Bristol County', 'state': 'Massachusetts', 'postcode': '02740', 'country': 'United States', 'country_code': 'us'}
6256 CORONA DEL MAR, CALIFORNIA, UNITED STATES  {'suburb': 'Corona del Mar', 'city': 'Newport Beach', 'county': 'Orange County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
6257 SECAUCUS, NJ, NEW JERSEY, UNITED STATES {'town': 'Secauc

In [12]:
print(len(errores), errores)

867 ['PREFER NOT TO ANSWER, MARYLAND, USA', 'NYC REMOTELY, NEW YORK, US', 'PREFER NOT TO ANSWER, CALIFORNIA, USA', 'DETROIT METRO AREA, MICHIGAN, UNITED STATES', 'SMALL CITY, REMOTE, NATIONAL COMPANY, FLORIDA, UNITED STATES', 'GORHAMPORTLAND, MAINE, US', 'WESTCHESTERNYC, NEW YORK, US', 'SAN JOSE, CALIFORNIA, US', 'TOO IDENTIFIABLE, GEORGIA, USA', 'CHICAGO AREA MOSTLY, BUT ALSO THE US AND CANADA, ILLINOIS, UNITED STATES', 'GREATER BOSTON AREA, MASSACHUSETTS, USA', 'CHICAGO REMOTE , ILLINOIS, UNITED STATES', 'HUNTINGTON REMOTE, HQ IS IN CHARLESTON, WEST VIRGINIA, USA', 'TWIN CITIES METRO AREA, MINNESOTA, UNITED STATES', 'DFW AREA, TEXAS, UNITED STATES', 'FULLY REMOTE GREATER BOSTON, MASSACHUSETTS, USA', 'PREFER NOT TO SAY MONTANA IS SMALL, MONTANA, UNITED STATES', 'PANHANDLE REGION, FLORIDA, US', 'I WORK REMOTELY, NEW YORK, USA', 'REMOTE HOME, NEW YORK, UNITED STATES', 'WORK FROM HOME , MASSACHUSETTS, UNITED STATES', 'VERYSMALL TOWN, IOWA, US', 'TWIN CITIES SUBURBS , MINNESOTA, UNITED ST

Como se puede observar, hay 867 casos que presenatron algún error. En muchos de esos casis parece haber errores de ortografía, palabaras que no se deberían utilizar, o datos como ciudad faltantes. Primero nos vamos a ocupar de estos caso de error y después revisaremos la información encontrada con geocode. 

La primera aproximación que haremos, es únicamente buscar la ciudad que las personas pusieron. Esto reduciria los casos de error (cuando la gente puso el pais mal. El problema de esto, radica en que el sistema puede asumir una ciudad que está en otro pais.

Por otro lado, no se porque cada vez que se llama la función, sale que no se detectan algunas opciones que después se detectan si se vuelve a correr. Por lo tanto se hace un while que recorre todo hasta que pase directo sin encontrar coincidencias en la ciudad

In [13]:
contador = 1
while contador > 0:
    contador = 0
    for c in errores:
        try:
            lugares[c] = geolocator.geocode(c.replace(".", "").split(",")[0], exactly_one=True,language="en", namedetails=True, addressdetails=True).raw["address"]
            errores.remove(c)
            contador += 1
            print(contador, c, lugares[c])
        except:
            continue

1 DETROIT METRO AREA, MICHIGAN, UNITED STATES {'road': 'Detroit Street', 'quarter': 'Pinagkaisahan', 'suburb': 'Scout Area', 'city_district': '4th District', 'city': 'Quezon City', 'state_district': 'Eastern Manila District', 'region': 'Metro Manila', 'postcode': '1111', 'country': 'Philippines', 'country_code': 'ph'}
2 SAN JOSE, CALIFORNIA, US {'city': 'San Jose', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
3 CHICAGO REMOTE , ILLINOIS, UNITED STATES {'building': 'Remote Parking ATS Station (Closed)', 'road': 'Coffey Road', 'suburb': "O'Hare", 'city': 'Chicago', 'municipality': 'Jefferson Township', 'county': 'Cook County', 'state': 'Illinois', 'postcode': '60666', 'country': 'United States', 'country_code': 'us'}
4 REMOTE HOME, NEW YORK, UNITED STATES {'road': 'Remote Street', 'residential': 'Modern Manor Mobile Home Park', 'municipality': 'Scott Township', 'county': 'Johnson County', 'state': 'Iowa', 'postcode': '52240', 'c

41 ATLANTA METRO AREA, GEORGIA, US {'road': 'Atlanta', 'suburb': 'Port Area', 'city_district': 'Fifth District', 'city': 'Manila', 'state_district': 'Capital District', 'region': 'Metro Manila', 'postcode': '1018', 'country': 'Philippines', 'country_code': 'ph'}
42 POOLER, GA, GEORGIA, UNITED STATESP {'town': 'Pooler', 'county': 'Chatham County', 'state': 'Georgia', 'postcode': '31322', 'country': 'United States', 'country_code': 'us'}
43 BELMONT, CA SF BAY AREA, CALIFORNIA, USA {'village': 'Belmont', 'municipality': 'Molsheim', 'county': 'Bas-Rhin', 'state': 'Grand Est', 'region': 'Metropolitan France', 'postcode': '67130', 'country': 'France', 'country_code': 'fr'}
44 REMOTE, NEW JERSEY, UNITED STATTES {'hamlet': 'Remote', 'county': 'Coos County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
45 CHATTANOOGA, GEORGIA, TENNESSEE, UNITED STATE {'city': 'Chattanooga', 'county': 'Hamilton County', 'state': 'Tennessee', 'postcode': '818', 'country': 'United States', 

77 COLORADO SPRINGS, COLORADO, US OF A {'city': 'Colorado Springs', 'county': 'El Paso County', 'state': 'Colorado', 'postcode': '80903', 'country': 'United States', 'country_code': 'us'}
78 BEAVERTON, OR PORTLAND SUBURB, OREGON, USA {'city': 'Beaverton', 'county': 'Washington County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
79 MONROE, CONNECTICUT, UNITES STATES {'county': 'Monroe County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
80 PROVIDENCE, MASSACHUSETTS, RHODE ISLAND, UNITED STATES {'city': 'Providence', 'county': 'Providence County', 'state': 'Rhode Island', 'country': 'United States', 'country_code': 'us'}
81 ROSSLYN, DISTRICT OF COLUMBIA, VIRGINIA, UNITED STATES {'railway': 'Rosslyn', 'house_number': '1850', 'road': 'North Moore Street', 'suburb': 'Rosslyn', 'city': 'Arlington', 'county': 'Arlington County', 'state': 'Virginia', 'postcode': '22209', 'country': 'United States', 'country_code': 'us'}
82 PORTLAND, OREGON, 

115 NY SUBURB, NEW JERSEY, UNITED STATES {'tourism': 'Przykopa suburb', 'road': 'Przykopa', 'municipality': 'Cieszyn', 'county': 'Cieszyn County', 'state': 'Silesian Voivodeship', 'postcode': '43-400', 'country': 'Poland', 'country_code': 'pl'}
116 REMOTE, NORTH CAROLINA, UNITED STATES  {'hamlet': 'Remote', 'county': 'Coos County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
117 LOS ANGELES , ARIZONA, CALIFORNIA, NEVADA, TEXAS, USA {'city': 'Los Angeles', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
118 SAN FRANSISCO, CALIFORNIA, USA {'hamlet': 'San Fransisco', 'village': 'Tilipulo', 'city': 'Latacunga', 'county': 'Latacunga', 'state': 'Cotopaxi', 'postcode': 'EC050101', 'country': 'Ecuador', 'country_code': 'ec'}
119 RURAL AREA, NEW YORK, USA {'landuse': 'Rural area', 'hamlet': 'El Ceibal', 'town': 'Rocafuerte', 'municipality': 'Parroquia Rocafuerte', 'county': 'Rocafuerte', 'state': 'Manabí', 'countr

155 PITTSBURGH, PENNSYLVANIA, I EARN COMMISSION ON SALES IF I MEET QUOTA, IM GUARANTEED ANOTHER K MIN LAST YEAR I EARNED AN ADDITIONAL K ITS NOT UNCOMMON FOR PEOPLE IN MY SPACE TO EARN K AFTER COMMISSION  {'city': 'Pittsburgh', 'county': 'Allegheny County', 'state': 'Pennsylvania', 'country': 'United States', 'country_code': 'us'}
156 DAVENPORT AREA, IOWA, UNITED STATES {'natural': 'Davenport Point', 'city': 'Area C (South Skeena)', 'county': 'North Coast Regional District', 'state': 'British Columbia', 'country': 'Canada', 'country_code': 'ca'}
157 SEATLE, WA, WASHINGTON, UNITED STATES {'road': 'Seatle', 'municipality': 'Ambato', 'county': 'Ambato', 'state': 'Tungurahua', 'postcode': '18050', 'country': 'Ecuador', 'country_code': 'ec'}
158 SEATTLE, WASHINGTON, UNITEDSTATES {'city': 'Seattle', 'county': 'King County', 'state': 'Washington', 'country': 'United States', 'country_code': 'us'}
159 WASHINGTON, DC IM REMOTE, BUT OFFICE IS IN DC, DISTRICT OF COLUMBIA, UNITED STATES {'city': '

194 NORTHERN VIRGINIA WASHINGTON, DC METRO, VIRGINIA, USA {'amenity': 'Northern Virginia Community College - Alexandria Campus', 'house_number': '5000', 'road': 'Dawes Avenue', 'neighbourhood': 'John Adams', 'hamlet': 'Washington Forest', 'city': 'Alexandria', 'state': 'Virginia', 'postcode': '22311', 'country': 'United States', 'country_code': 'us'}
195 VANCOUVER, OHIO, WASHINGTON, UNITED STATES {'city': 'Vancouver', 'municipality': 'District of North Vancouver', 'county': 'Metro Vancouver Regional District', 'state': 'British Columbia', 'country': 'Canada', 'country_code': 'ca'}
196 NEW YOR, NEW YORK, US {'road': 'New Walk', 'suburb': 'Bishophill', 'city': 'York', 'county': 'York', 'state_district': 'Yorkshire and the Humber', 'state': 'England', 'postcode': 'YO1 9WJ', 'country': 'United Kingdom', 'country_code': 'gb'}
197 ANON, MASSACHUSETTS, US {'village': 'Annone Veneto', 'county': 'Venezia', 'state': 'Veneto', 'country': 'Italy', 'country_code': 'it'}
198 SHREVEPORT, LOUISIANA, U

234 MCLEAN, VIRGINIA, UNITES STATES {'county': 'McLean County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
235 VARIES, NEW YORK, USA {'isolated_dwelling': 'Les Varies', 'village': 'Trébédan', 'municipality': 'Dinan', 'county': "Côtes-d'Armor", 'state': 'Brittany', 'region': 'Metropolitan France', 'postcode': '22980', 'country': 'France', 'country_code': 'fr'}
236 TWIN CITIES AREA, MINNESOTA, US {'building': 'Castel Area Health Centre', 'road': 'Constantin Lane', 'suburb': 'Castel', 'city': 'Vacoas-Phoenix', 'county': 'Vacoas-Phoenix', 'state': 'Plaines Wilhems', 'postcode': '74232', 'country': 'Mauritius', 'country_code': 'mu'}
237 SAN JOSE, CA, CALIFORNIA, Y {'city': 'San Jose', 'county': 'Santa Clara County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
238 PLEASANT PRARIE, WISCONSIN, USA  {'amenity': 'Pleasant Hill School', 'road': 'Prarie Lane', 'county': 'McCurtain County', 'state': 'Oklahoma', 'country': 'United States', 'co

275 SAN FRANCISCO, BUT COMPANY IS BOSTON BASED, CALIFORNIA, US {'city': 'San Francisco', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
276 EUGENE, OREGON, UNITED STATE {'city': 'Eugene', 'county': 'Lane County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
277 MINNEAPOLIS, MINNESOTA, UNITED SATES {'city': 'Minneapolis', 'county': 'Hennepin County', 'state': 'Minnesota', 'postcode': '55488', 'country': 'United States', 'country_code': 'us'}
278 ALL, TRAVEL, NORTH CAROLINA, USA {'county': 'Allen County', 'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
279 STL, MISSISSIPPI, MISSOURI, USA {'state': 'Southland', 'country': 'New Zealand', 'country_code': 'nz'}
280 LOS ANGELES, CALIFORNIA, MARYLAND, UNITED STATES {'city': 'Los Angeles', 'county': 'Los Angeles County', 'state': 'California', 'country': 'United States', 'country_code': 'us'}
281 TERRE HAUTE, INDIANA, UNITED STATES IS AMERICA {'city': 'Terre Haute', 'county': 

32 CHICAGO SUBURBS, INDIANA, USA {'suburb': 'Chicago', 'town': 'Paarl', 'city': 'Drakenstein Local Municipality', 'county': 'Cape Winelands District Municipality', 'state': 'Western Cape', 'postcode': '7646', 'country': 'South Africa', 'country_code': 'za'}
33 ALEXANDRIA, VA, DISTRICT OF COLUMBIA, US {'city': 'Alexandria', 'state': 'Alexandria Governorate', 'postcode': '21519', 'country': 'Egypt', 'country_code': 'eg'}
34 PORTLAND, CALIFORNIA, OREGON, UNITED STATES {'city': 'Portland', 'county': 'Multnomah County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
35 PORTLAND, OREGON, CURRENTLY FINANCE {'city': 'Portland', 'county': 'Multnomah County', 'state': 'Oregon', 'country': 'United States', 'country_code': 'us'}
36 REMOVE, VIRGINIA, USA {'waterway': 'East Fork Point Remove Site Three Dam', 'county': 'Conway County', 'state': 'Arkansas', 'country': 'United States', 'country_code': 'us'}
37 WASHINGTON DC, DISTRICT OF COLUMBIA, UXZ {'city': 'Washington', 'state'

72 EAST ROCKAWAY LONG ISLAND, NEW YORK, USA {'shop': 'Hearing Center of Long Island', 'house_number': '46', 'road': 'Rockaway Avenue', 'town': 'Valley Stream', 'municipality': 'Town of Hempstead', 'county': 'Nassau County', 'state': 'New York', 'postcode': '11580', 'country': 'United States', 'country_code': 'us'}
73 BARDSTOWN, KY  STORE IS LOCATED IN FRANKFORT, KENTUCKY, USA {'town': 'Bardstown', 'city': 'Bardstown', 'county': 'Nelson County', 'state': 'Kentucky', 'postcode': '40004', 'country': 'United States', 'country_code': 'us'}
74 SAN FRANSICO, CALIFORNIA, UNITED STATES {'locality': 'San Fransico (6)', 'town': 'Contadero', 'county': 'Contadero', 'state_district': 'Ex-Providencia de Obando', 'state': 'Nariño', 'country': 'Colombia', 'country_code': 'co'}
75 BLANK, MISSISSIPPI, I WAS BROUGHT IN ON THIS SALARY TO HELP WITH THE EHR AND VERY QUICKLY WAS PROMOTED TO CURRENT POSITION BUT COMPENSATION WAS NOT ALTERED  {'hamlet': 'Blank', 'county': 'Frederick County', 'state': 'Maryland'

109 NA, ALABAMA, NA {'country': 'Namibia', 'country_code': 'na'}
110 NEW YORK CITY , NEW YORK, VIRGINIA, USA  {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
111 DECLINE, NEW JERSEY, UNITED STATES {'industrial': 'Decline 4 South', 'suburb': 'Moses Kotane Ward 7', 'city': 'Moses Kotane Local Municipality', 'county': 'Bojanala Platinum District Municipality', 'state': 'North West', 'country': 'South Africa', 'country_code': 'za'}
112 RALEIGH, CALIFORNIA, ILLINOIS, MASSACHUSETTS, NORTH CAROLINA, SOUTH CAROLINA, VIRGINIA, USA  {'city': 'Raleigh', 'county': 'Wake County', 'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
113 CHICAGO, ILLINOIS, UNITED STATE OF AMERICA {'city': 'Chicago', 'county': 'Cook County', 'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
114 BOISE, IDAHO, UNITED STATES OF AMERICAN {'city': 'Boise', 'county': 'Ada County', 'state': 'Idaho', 'postcode': '83701', 'country': 'Unite

Como se puede observar, se disminuye el caso de errores. Por lo tanto, vamos a seguir con el siguiente nivel (intentando únicamente los States de las entradas que mantienen su error).

In [14]:
contador = 1
while contador > 0:
    contador = 0
    for c in errores:
        try:
            lugares[c] = geolocator.geocode(c.replace(".", "").split(",")[1], exactly_one=True,language="en", namedetails=True, addressdetails=True).raw["address"]
            errores.remove(c)
            contador += 1
            print(contador, c, lugares[c])
        except:
            continue

1 PREFER NOT TO ANSWER, MARYLAND, USA {'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
2 PREFER NOT TO ANSWER, CALIFORNIA, USA {'state': 'California', 'country': 'United States', 'country_code': 'us'}
3 WESTCHESTERNYC, NEW YORK, US {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
4 GREATER BOSTON AREA, MASSACHUSETTS, USA {'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
5 TWIN CITIES METRO AREA, MINNESOTA, UNITED STATES {'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
6 FULLY REMOTE GREATER BOSTON, MASSACHUSETTS, USA {'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
7 PANHANDLE REGION, FLORIDA, US {'state': 'Florida', 'country': 'United States', 'country_code': 'us'}
8 WORK FROM HOME , MASSACHUSETTS, UNITED STATES {'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
9 LAS VEGAS TECHINICALLY REMOTE, NEVADA, UNITED STATES 

68 PREFER NOT TO ANSWER, ILLINOIS, USA {'state': 'Illinois', 'country': 'United States', 'country_code': 'us'}
69 SMALL CITYACTUAL CITY WOULD GIVE AWAY THE COMPANY, CALIFORNIA, USA {'state': 'California', 'country': 'United States', 'country_code': 'us'}
70 I WORK REMOTELY BUT IN NONCOVID TIMES I WORK AT CLIENT SITES THROUGHOUT THE US, NEW YORK, UNITED STATES {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
71 ATLANTADECATUR, GEORGIA, UNITED STATES {'country': 'Georgia', 'country_code': 'ge'}
72 ONE OF THE LARGEST IN THE STATE, WISCONSIN, USA {'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
73 OUTSIDE THE TWIN CITIES, MINNESOTA, USA {'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
74 NOT SAYING , IOWA, UNITED STATES  {'state': 'Iowa', 'country': 'United States', 'country_code': 'us'}
75 I WORK REMOTELY WITH CLIENTS ACROSS THE COUNTRY, INDIANA, UNITED STATES {'state': 'Indiana', 'country': 'United

135 SEATLLE, WASHINGTON, USA {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
136 VERNON  REMOTE POSITION THOUGH , INDIANA, USA {'state': 'Indiana', 'country': 'United States', 'country_code': 'us'}
137 MINNEAPOLISST PAUL, MINNESOTA, US {'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
138 SEATTLE COMPANY IS IN REDMOND, WASHINGTON, USA {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
139 PREFER NOT TO ANSWER, LOUISIANA, UNITED STATES {'state': 'Louisiana', 'country': 'United States', 'country_code': 'us'}
140 GREATER SEATTLE AREA, WASHINGTON, UNITED STATES  {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
141 DMV METRO AREA, MARYLAND, VIRGINIA, USA {'state': 'Maryland', 'country': 'United States', 'country_code': 'us'}
142 CANT SAY, MISSISSIPPI, UNITED STATES {'state': 'Mississippi', 'country': 

204 OAKLAND AND HAYWARD, CALIFORNIA, UNITED STATES {'state': 'California', 'country': 'United States', 'country_code': 'us'}
205 PREFER NOT TO SAY, LOUISIANA, USA {'state': 'Louisiana', 'country': 'United States', 'country_code': 'us'}
206 MILWAUKEE REMOTE, WISCONSIN, USA {'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
207 SF BAY AREA REMOTE, CALIFORNIA, US {'state': 'California', 'country': 'United States', 'country_code': 'us'}
208 MILWAUKEEREMOTE, WISCONSIN, UNITED STATES {'state': 'Wisconsin', 'country': 'United States', 'country_code': 'us'}
209 RALEIGH DURHAM AREA , NORTH CAROLINA, UNITED STATES {'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
1 NYC REMOTELY, NEW YORK, US {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
2 TOO IDENTIFIABLE, GEORGIA, USA {'country': 'Georgia', 'country_code': 'ge'}
3 HUNTINGTON REMOTE, HQ IS IN CHARLESTON, WEST VIRGINIA, USA {'locality': 'Charleston', '

60 BRYANCOLLEGE STATION, TEXAS, US {'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
61 WINSTONSALEM, NORTH CAROLINA, USA {'state': 'North Carolina', 'country': 'United States', 'country_code': 'us'}
62 LOUISVILLE REMOTE, KENTUCKY, USA {'state': 'Kentucky', 'country': 'United States', 'country_code': 'us'}
63 DECLINE TO ANSWER, UTAH, UNITED STATES {'state': 'Utah', 'country': 'United States', 'country_code': 'us'}
64 FULLY REMOTE, WASHINGTON, UNITED STATES {'city': 'Washington', 'state': 'District of Columbia', 'country': 'United States', 'country_code': 'us'}
65 OGDEN  BUT I WORK REMOTE COMPANY IS BASED IN MD, UTAH, UNITED STATES {'state': 'Utah', 'country': 'United States', 'country_code': 'us'}
66 GREATER MINNEAPOLIS METRO AREA, MINNESOTA, UNITED STATES {'state': 'Minnesota', 'country': 'United States', 'country_code': 'us'}
67 NY METRO AREA BUT NOT NYC, NEW YORK, USA {'city': 'New York', 'state': 'New York', 'country': 'United States', 'country_code': 'us'}
68 RE

23 LYNNFIELD BOSTON METRO AREA, MASSACHUSETTS, UNITED STATES {'state': 'Massachusetts', 'country': 'United States', 'country_code': 'us'}
24 PREFER NOT TO SAY, HAWAII, USA {'state': 'Hawaii', 'country': 'United States', 'country_code': 'us'}
25 GROVE CITY  REMOTE, OHIO, USA {'state': 'Ohio', 'country': 'United States', 'country_code': 'us'}
26 ALLENPLANO, TEXAS, UNITED STATES {'state': 'Texas', 'country': 'United States', 'country_code': 'us'}
27 REMOTELY  STAMFORD HQ, CONNECTICUT, USA {'state': 'Connecticut', 'country': 'United States', 'country_code': 'us'}
28 ANAHEIMSANTA ANAIRVINE METRO REGION, CALIFORNIA, UNITED STATES {'state': 'California', 'country': 'United States', 'country_code': 'us'}
29 I WORK IN A RURAL AREA AND CANNOT ANSWER THIS QUESTION WHILE MAINTAINING ANONYMITY, MAINE, UNITED STATES {'state': 'Maine', 'country': 'United States', 'country_code': 'us'}
30 THE OFFICE IS IN SCHAUMBURG I WORK REMOTELY, ILLINOIS, UNITED STATES {'state': 'Illinois', 'country': 'United Stat

Por último, haremos lo mismo pero con el pais.

In [15]:
contador = 1
while contador > 0:
    contador = 0
    for c in errores:
        try:
            lugares[c] = geolocator.geocode(c.replace(".", "").split(",")[-1], exactly_one=True,language="en", namedetails=True, addressdetails=True).raw["address"]
            errores.remove(c)
            contador += 1
            print(contador, c, lugares[c])
        except:
            continue

1 CHICAGO AREA MOSTLY, BUT ALSO THE US AND CANADA, ILLINOIS, UNITED STATES {'country': 'United States', 'country_code': 'us'}
2 JOB IS BASED IN DC, BUT I GO TO WHERE DISASTERS ARE , DISTRICT OF COLUMBIA, USA {'country': 'United States', 'country_code': 'us'}
3 COMPANY IS IN NYC, IM REMOTE IN BOSTON, NEW YORK, UNITED STATES {'country': 'United States', 'country_code': 'us'}
4 STILLWATER WI BASED COMPANY, OFFICE IN MN, MINNESOTA, US {'country': 'United States', 'country_code': 'us'}
5 CORP HQ IS IN CHARLESTON, SC I WFH, MINNESOTA, US {'country': 'United States', 'country_code': 'us'}
6 MONTCLAIR NOT ACTUAL CITY, BUT SAME REGION FOR ANONYMITY, NEW JERSEY, USA {'country': 'United States', 'country_code': 'us'}
7 TELECOMMUTE FROM ANAHEIM, CA EMPLOYER OFFICE IN RANCHO CUCAMONGA, CA, CALIFORNIA, UNITED STATES {'country': 'United States', 'country_code': 'us'}
8 OFFICE WAS IN CHICAGO, NOW WFH IN WI, ILLINOIS, WISCONSIN, USA {'country': 'United States', 'country_code': 'us'}
9 I WORK REMOTELY, 

In [17]:
errores

[]

Como se puede observar, todas las ubicaciones ya tienen al menos un objeto referenciado. Es importante aclarar que claramente esto puede tener algunos errores, pero de igual manera es una buena forma de estandarización. 

Ahora, se crea una nueva variable Pais, con los paises enocntrados en el método. Pude evidenciar que en dos casos no se encontró ningún pais, aún así ambos casos son en Alaska y se refiere a lugares en USA por lo tanto, cree una función que retorna el pais y si no encuentra entonces asigna "United States"

In [29]:
def extaer_pais(x):
    try:
        return(x["country"])
    except:
        return("United States")
    
df["Pais"] = df["Lugar"].apply(lambda x: extaer_pais(lugares[x]))

Por otro lado, hacemos lo mismo con la ciudad. Este caso es más delicado porque muchos sitios no se encontró la ciudad. por lo tanto (y después de muchas iteraciones en el proceso) se llegó a la siguiente conclusión:

Primero se eliminan todos los valores que en lugar tienen NAN (esto se ha debido hacer antes pero se me olvidó y en este punto se demora mucho corriendo todo el código)

después, se extrae los que tienen "city"
Tercero, se extrae los que tienen "town"
porteriormente, los que tiene. "place"
Quinto, los que tienen "suburb"
sexto, los que tiene "village"
septimo, los que tienen "locality"
octavo, los que tienen "county". En este punto nos vamos extendiendo a territorios más grandes.

Despues de hacer esto se mantiene la incógnita en 421 registros. Es decir, registros que no tienen ciudad, solo tienen estado o pais. Para estos casos vamos a hacer un proceso un poco diferente. Si tiene estado, entonces vamos a coger el punto centralk del estado y si solo tiene pais, el punto central del pais. Para eso creamos la función ubicacion_central

9. Se hace todo el proceso descrito anteriormente. 
10. Si persiste problema se hizo manualmente, fueron solo 3 casos.

In [35]:
df = df[df["Lugar"] != "NAN"]

In [89]:
def ubicacion_central(lugar):
    loc = geolocator.geocode(lugar, exactly_one=True,language="en", addressdetails=True,).raw
    location = geolocator.reverse(loc["lat"]+","+loc["lon"])
    return(location.raw["address"])

In [94]:
def extaer_ciudad(x):
    try:
        return(x["city"])
    except:
        try:
            return(x["town"])
        except:
            try:
                return(x["place"])
            except:
                try:
                    return(x["suburb"])
                except:
                    try:
                        return(x["village"])
                    except:
                        try:
                            return(x["locality"])
                        except:
                            try:
                                return(x["county"])
                            except:
                                try:
                                    return(ubicacion_central(x["state"])["county"])
                                except:
                                    try:
                                        return(ubicacion_central(x["country"])["county"])
                                    except:
                                        return("")



In [96]:
df["Ciudad"] = df["Lugar"].apply(lambda x: extaer_ciudad(lugares[x]))

<ipython-input-96-6b7264b32797>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ciudad"] = df["Lugar"].apply(lambda x: extaer_ciudad(lugares[x]))


In [98]:
df[df["Ciudad"] == ""]

Timestamp How old are you?                       Industry  \
2006   4/27/2021 11:36:17            35-44                     Nonprofits   
16808  4/28/2021 18:34:04            25-34   Engineering or Manufacturing   
26562  7/20/2021 14:58:53         under 18  Accounting, Banking & Finance   

                    Job title  \
2006   Program administrator    
16808         Field Geologist   
26562                      na   

                         Additional context on job title Annual salary  \
2006   My official title is program assistant but I a...        64,000   
16808                                                NaN        61,000   
26562                                                 na            00   

       Other monetary comp Currency Currency - other  \
2006                1500.0      USD              NaN   
16808                  0.0      USD              NaN   
26562                  0.0      USD               na   

      Additional context on income  ... Years of experience in field  \
2006                           NaN  ...                11 - 20 years   
16808                          NaN  ...                  2 - 4 years   
26562                           na  ...               1 year or less   

      Highest level of education completed Gender  \
2006                        College degree  Woman   
16808                      Master's degree  Woman   
26562                          High School    Man   

                                                    Race salario_anual  \
2006                                               White   250721280.0   
16808  Another option not listed here or prefer not t...   238968720.0   
26562                            Asian or Asian American           0.0   

      compensaciones Total_ingresos  \
2006      58762800.0    309484080.0   
16808            0.0    238968720.0   
26562            0.0            0.0   

                                              Lugar         Pais  Ciudad  
2006               RURAL  NORTHERN, MINNESOTA, USA      Tanzania          
16808  SOUTH, FLORIDA, GEORGIA, SOUTH CAROLINA, USA  South Korea          
26562                               NA, ALABAMA, NA      Namibia          

[3 rows x 24 columns]

In [99]:
df.loc[2006, "Pais"] = "United States"
df.loc[2006, "Ciudad"] = "Saint Paul"
df.loc[16808, "Pais"] = "United States"
df.loc[16808, "Ciudad"] = "Georgia"
df.loc[26562, "Pais"] = "United States"
df.loc[26562, "Ciudad"] = "Montgomery"

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [101]:
df.to_csv("Corregido.csv")